/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  AnnouncementDetailResponseDto,
  AnnouncementListResponseDto,
  AnnouncementsControllerListParams,
  CreateAnnouncementRequestDto,
  RemoveAnnouncementResponseDto,
  UpdateAnnouncementRequestDto
} from '../orvalSchemas';



/**
 * @summary 공지사항 목록 조회
 */
export type announcementsControllerListResponse200 = {
  data: AnnouncementListResponseDto
  status: 200
}
    
export type announcementsControllerListResponseSuccess = (announcementsControllerListResponse200) & {
  headers: Headers;
};
;

export type announcementsControllerListResponse = (announcementsControllerListResponseSuccess)

export const getAnnouncementsControllerListUrl = (params?: AnnouncementsControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/announcements?${stringifiedParams}` : `/announcements`
}

export const announcementsControllerList = async (params?: AnnouncementsControllerListParams, options?: RequestInit): Promise<announcementsControllerListResponse> => {
  
  const res = await fetch(getAnnouncementsControllerListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: announcementsControllerListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as announcementsControllerListResponse
}


/**
 * @summary 공지사항 생성
 */
export type announcementsControllerCreateResponse200 = {
  data: AnnouncementDetailResponseDto
  status: 200
}

export type announcementsControllerCreateResponse400 = {
  data: void
  status: 400
}

export type announcementsControllerCreateResponse401 = {
  data: void
  status: 401
}
    
export type announcementsControllerCreateResponseSuccess = (announcementsControllerCreateResponse200) & {
  headers: Headers;
};
export type announcementsControllerCreateResponseError = (announcementsControllerCreateResponse400 | announcementsControllerCreateResponse401) & {
  headers: Headers;
};

export type announcementsControllerCreateResponse = (announcementsControllerCreateResponseSuccess | announcementsControllerCreateResponseError)

export const getAnnouncementsControllerCreateUrl = () => {


  

  return `/announcements`
}

export const announcementsControllerCreate = async (createAnnouncementRequestDto: CreateAnnouncementRequestDto, options?: RequestInit): Promise<announcementsControllerCreateResponse> => {
    const formData = new FormData();
formData.append(`title`, createAnnouncementRequestDto.title);
formData.append(`body`, createAnnouncementRequestDto.body);
if(createAnnouncementRequestDto.isPinned !== undefined) {
 formData.append(`isPinned`, createAnnouncementRequestDto.isPinned.toString())
 }
if(createAnnouncementRequestDto.isPublished !== undefined) {
 formData.append(`isPublished`, createAnnouncementRequestDto.isPublished.toString())
 }
if(createAnnouncementRequestDto.publishedAt !== undefined) {
 formData.append(`publishedAt`, createAnnouncementRequestDto.publishedAt);
 }
if(createAnnouncementRequestDto.image !== undefined) {
 formData.append(`image`, createAnnouncementRequestDto.image);
 }

  const res = await fetch(getAnnouncementsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: announcementsControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as announcementsControllerCreateResponse
}


/**
 * @summary 공지사항 상세 조회
 */
export type announcementsControllerFindOneResponse200 = {
  data: AnnouncementDetailResponseDto
  status: 200
}
    
export type announcementsControllerFindOneResponseSuccess = (announcementsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type announcementsControllerFindOneResponse = (announcementsControllerFindOneResponseSuccess)

export const getAnnouncementsControllerFindOneUrl = (id: string,) => {


  

  return `/announcements/${id}`
}

export const announcementsControllerFindOne = async (id: string, options?: RequestInit): Promise<announcementsControllerFindOneResponse> => {
  
  const res = await fetch(getAnnouncementsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: announcementsControllerFindOneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as announcementsControllerFindOneResponse
}


/**
 * @summary 공지사항 수정
 */
export type announcementsControllerUpdateResponse200 = {
  data: AnnouncementDetailResponseDto
  status: 200
}

export type announcementsControllerUpdateResponse400 = {
  data: void
  status: 400
}

export type announcementsControllerUpdateResponse401 = {
  data: void
  status: 401
}
    
export type announcementsControllerUpdateResponseSuccess = (announcementsControllerUpdateResponse200) & {
  headers: Headers;
};
export type announcementsControllerUpdateResponseError = (announcementsControllerUpdateResponse400 | announcementsControllerUpdateResponse401) & {
  headers: Headers;
};

export type announcementsControllerUpdateResponse = (announcementsControllerUpdateResponseSuccess | announcementsControllerUpdateResponseError)

export const getAnnouncementsControllerUpdateUrl = (id: string,) => {


  

  return `/announcements/${id}`
}

export const announcementsControllerUpdate = async (id: string,
    updateAnnouncementRequestDto: UpdateAnnouncementRequestDto, options?: RequestInit): Promise<announcementsControllerUpdateResponse> => {
    const formData = new FormData();
if(updateAnnouncementRequestDto.title !== undefined) {
 formData.append(`title`, updateAnnouncementRequestDto.title);
 }
if(updateAnnouncementRequestDto.body !== undefined) {
 formData.append(`body`, updateAnnouncementRequestDto.body);
 }
if(updateAnnouncementRequestDto.isPinned !== undefined) {
 formData.append(`isPinned`, updateAnnouncementRequestDto.isPinned.toString())
 }
if(updateAnnouncementRequestDto.isPublished !== undefined) {
 formData.append(`isPublished`, updateAnnouncementRequestDto.isPublished.toString())
 }
if(updateAnnouncementRequestDto.publishedAt !== undefined) {
 formData.append(`publishedAt`, updateAnnouncementRequestDto.publishedAt);
 }
if(updateAnnouncementRequestDto.image !== undefined) {
 formData.append(`image`, updateAnnouncementRequestDto.image);
 }

  const res = await fetch(getAnnouncementsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: announcementsControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as announcementsControllerUpdateResponse
}


/**
 * @summary 공지사항 삭제(비활성화)
 */
export type announcementsControllerRemoveResponse200 = {
  data: RemoveAnnouncementResponseDto
  status: 200
}

export type announcementsControllerRemoveResponse401 = {
  data: void
  status: 401
}
    
export type announcementsControllerRemoveResponseSuccess = (announcementsControllerRemoveResponse200) & {
  headers: Headers;
};
export type announcementsControllerRemoveResponseError = (announcementsControllerRemoveResponse401) & {
  headers: Headers;
};

export type announcementsControllerRemoveResponse = (announcementsControllerRemoveResponseSuccess | announcementsControllerRemoveResponseError)

export const getAnnouncementsControllerRemoveUrl = (id: string,) => {


  

  return `/announcements/${id}`
}

export const announcementsControllerRemove = async (id: string, options?: RequestInit): Promise<announcementsControllerRemoveResponse> => {
  
  const res = await fetch(getAnnouncementsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: announcementsControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as announcementsControllerRemoveResponse
}


