/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  AuthControllerDevLogin400,
  AuthControllerDevLogin403,
  AuthControllerGoogleCallback400,
  AuthControllerGoogleCallbackParams,
  AuthControllerGoogleLogin400,
  AuthControllerKakaoCallback400,
  AuthControllerKakaoCallbackParams,
  AuthControllerKakaoLogin400,
  AuthControllerLogout400,
  AuthControllerLogout401,
  AuthControllerRefresh400,
  AuthControllerRefresh401,
  AuthSuccessResponseDto
} from '../orvalSchemas';



/**
 * 실제 OAuth 과정 없이 관리자 계정으로 로그인하고 쿠키를 발급받습니다. (DEPLOY_ENV !== production 환경에서만 사용 가능)
 * @summary 테스트/개발용 관리자 로그인
 */
export type authControllerDevLoginResponse200 = {
  data: AuthSuccessResponseDto
  status: 200
}

export type authControllerDevLoginResponse400 = {
  data: AuthControllerDevLogin400
  status: 400
}

export type authControllerDevLoginResponse403 = {
  data: AuthControllerDevLogin403
  status: 403
}
    
export type authControllerDevLoginResponseSuccess = (authControllerDevLoginResponse200) & {
  headers: Headers;
};
export type authControllerDevLoginResponseError = (authControllerDevLoginResponse400 | authControllerDevLoginResponse403) & {
  headers: Headers;
};

export type authControllerDevLoginResponse = (authControllerDevLoginResponseSuccess | authControllerDevLoginResponseError)

export const getAuthControllerDevLoginUrl = () => {


  

  return `/auth/dev/login`
}

export const authControllerDevLogin = async ( options?: RequestInit): Promise<authControllerDevLoginResponse> => {
  
  const res = await fetch(getAuthControllerDevLoginUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerDevLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerDevLoginResponse
}


/**
 * 구글 OAuth 인증 페이지로 리다이렉트합니다. 브라우저에서 직접 접근해야 합니다.
 * @summary 구글 로그인
 */
export type authControllerGoogleLoginResponse302 = {
  data: void
  status: 302
}

export type authControllerGoogleLoginResponse400 = {
  data: AuthControllerGoogleLogin400
  status: 400
}
    
;
export type authControllerGoogleLoginResponseError = (authControllerGoogleLoginResponse302 | authControllerGoogleLoginResponse400) & {
  headers: Headers;
};

export type authControllerGoogleLoginResponse = (authControllerGoogleLoginResponseError)

export const getAuthControllerGoogleLoginUrl = () => {


  

  return `/auth/google`
}

export const authControllerGoogleLogin = async ( options?: RequestInit): Promise<authControllerGoogleLoginResponse> => {
  
  const res = await fetch(getAuthControllerGoogleLoginUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerGoogleLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerGoogleLoginResponse
}


/**
 * 구글 OAuth 콜백을 처리합니다. 서버 내부에서 자동 호출되며, 클라이언트가 직접 호출하지 않습니다.
 * @summary 구글 로그인 콜백
 */
export type authControllerGoogleCallbackResponse200 = {
  data: string
  status: 200
}

export type authControllerGoogleCallbackResponse400 = {
  data: AuthControllerGoogleCallback400
  status: 400
}
    
export type authControllerGoogleCallbackResponseSuccess = (authControllerGoogleCallbackResponse200) & {
  headers: Headers;
};
export type authControllerGoogleCallbackResponseError = (authControllerGoogleCallbackResponse400) & {
  headers: Headers;
};

export type authControllerGoogleCallbackResponse = (authControllerGoogleCallbackResponseSuccess | authControllerGoogleCallbackResponseError)

export const getAuthControllerGoogleCallbackUrl = (params: AuthControllerGoogleCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/google/callback?${stringifiedParams}` : `/auth/google/callback`
}

export const authControllerGoogleCallback = async (params: AuthControllerGoogleCallbackParams, options?: RequestInit): Promise<authControllerGoogleCallbackResponse> => {
  
  const res = await fetch(getAuthControllerGoogleCallbackUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerGoogleCallbackResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerGoogleCallbackResponse
}


/**
 * 카카오 OAuth 인증 페이지로 리다이렉트합니다. 브라우저에서 직접 접근해야 합니다.
 * @summary 카카오 로그인
 */
export type authControllerKakaoLoginResponse302 = {
  data: void
  status: 302
}

export type authControllerKakaoLoginResponse400 = {
  data: AuthControllerKakaoLogin400
  status: 400
}
    
;
export type authControllerKakaoLoginResponseError = (authControllerKakaoLoginResponse302 | authControllerKakaoLoginResponse400) & {
  headers: Headers;
};

export type authControllerKakaoLoginResponse = (authControllerKakaoLoginResponseError)

export const getAuthControllerKakaoLoginUrl = () => {


  

  return `/auth/kakao`
}

export const authControllerKakaoLogin = async ( options?: RequestInit): Promise<authControllerKakaoLoginResponse> => {
  
  const res = await fetch(getAuthControllerKakaoLoginUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerKakaoLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerKakaoLoginResponse
}


/**
 * 카카오 OAuth 콜백을 처리합니다. 서버 내부에서 자동 호출되며, 클라이언트가 직접 호출하지 않습니다.
 * @summary 카카오 로그인 콜백
 */
export type authControllerKakaoCallbackResponse200 = {
  data: string
  status: 200
}

export type authControllerKakaoCallbackResponse400 = {
  data: AuthControllerKakaoCallback400
  status: 400
}
    
export type authControllerKakaoCallbackResponseSuccess = (authControllerKakaoCallbackResponse200) & {
  headers: Headers;
};
export type authControllerKakaoCallbackResponseError = (authControllerKakaoCallbackResponse400) & {
  headers: Headers;
};

export type authControllerKakaoCallbackResponse = (authControllerKakaoCallbackResponseSuccess | authControllerKakaoCallbackResponseError)

export const getAuthControllerKakaoCallbackUrl = (params: AuthControllerKakaoCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/kakao/callback?${stringifiedParams}` : `/auth/kakao/callback`
}

export const authControllerKakaoCallback = async (params: AuthControllerKakaoCallbackParams, options?: RequestInit): Promise<authControllerKakaoCallbackResponse> => {
  
  const res = await fetch(getAuthControllerKakaoCallbackUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerKakaoCallbackResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerKakaoCallbackResponse
}


/**
 * RefreshToken을 폐기하고 인증 쿠키를 즉시 만료 처리합니다.
 * @summary 로그아웃
 */
export type authControllerLogoutResponse204 = {
  data: void
  status: 204
}

export type authControllerLogoutResponse400 = {
  data: AuthControllerLogout400
  status: 400
}

export type authControllerLogoutResponse401 = {
  data: AuthControllerLogout401
  status: 401
}
    
export type authControllerLogoutResponseSuccess = (authControllerLogoutResponse204) & {
  headers: Headers;
};
export type authControllerLogoutResponseError = (authControllerLogoutResponse400 | authControllerLogoutResponse401) & {
  headers: Headers;
};

export type authControllerLogoutResponse = (authControllerLogoutResponseSuccess | authControllerLogoutResponseError)

export const getAuthControllerLogoutUrl = () => {


  

  return `/auth/logout`
}

export const authControllerLogout = async ( options?: RequestInit): Promise<authControllerLogoutResponse> => {
  
  const res = await fetch(getAuthControllerLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerLogoutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerLogoutResponse
}


/**
 * RefreshToken 쿠키를 이용해 새로운 AccessToken을 발급합니다.
 * @summary 액세스 토큰 갱신
 */
export type authControllerRefreshResponse204 = {
  data: void
  status: 204
}

export type authControllerRefreshResponse400 = {
  data: AuthControllerRefresh400
  status: 400
}

export type authControllerRefreshResponse401 = {
  data: AuthControllerRefresh401
  status: 401
}
    
export type authControllerRefreshResponseSuccess = (authControllerRefreshResponse204) & {
  headers: Headers;
};
export type authControllerRefreshResponseError = (authControllerRefreshResponse400 | authControllerRefreshResponse401) & {
  headers: Headers;
};

export type authControllerRefreshResponse = (authControllerRefreshResponseSuccess | authControllerRefreshResponseError)

export const getAuthControllerRefreshUrl = () => {


  

  return `/auth/refresh`
}

export const authControllerRefresh = async ( options?: RequestInit): Promise<authControllerRefreshResponse> => {
  
  const res = await fetch(getAuthControllerRefreshUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerRefreshResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerRefreshResponse
}


