/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  BackgroundRemovalRequestDto,
  BackgroundRemovalResponseDto
} from '../orvalSchemas';



/**
 * Recraft API를 통해 이미지 배경을 제거합니다. 유저별 분당 10회 제한이 적용됩니다.
 * @summary 이미지 배경 제거
 */
export type backgroundRemovalControllerRemoveBackgroundResponse200 = {
  data: BackgroundRemovalResponseDto
  status: 200
}

export type backgroundRemovalControllerRemoveBackgroundResponse400 = {
  data: void
  status: 400
}

export type backgroundRemovalControllerRemoveBackgroundResponse401 = {
  data: void
  status: 401
}
    
export type backgroundRemovalControllerRemoveBackgroundResponseSuccess = (backgroundRemovalControllerRemoveBackgroundResponse200) & {
  headers: Headers;
};
export type backgroundRemovalControllerRemoveBackgroundResponseError = (backgroundRemovalControllerRemoveBackgroundResponse400 | backgroundRemovalControllerRemoveBackgroundResponse401) & {
  headers: Headers;
};

export type backgroundRemovalControllerRemoveBackgroundResponse = (backgroundRemovalControllerRemoveBackgroundResponseSuccess | backgroundRemovalControllerRemoveBackgroundResponseError)

export const getBackgroundRemovalControllerRemoveBackgroundUrl = () => {


  

  return `/background-removal`
}

export const backgroundRemovalControllerRemoveBackground = async (backgroundRemovalRequestDto: BackgroundRemovalRequestDto, options?: RequestInit): Promise<backgroundRemovalControllerRemoveBackgroundResponse> => {
    const formData = new FormData();
formData.append(`file`, backgroundRemovalRequestDto.file);

  const res = await fetch(getBackgroundRemovalControllerRemoveBackgroundUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: backgroundRemovalControllerRemoveBackgroundResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as backgroundRemovalControllerRemoveBackgroundResponse
}


