/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  BatchControllerDevTriggerGeneration403,
  BatchControllerTriggerGeneration401,
  BatchTriggerResponseDto
} from '../orvalSchemas';



/**
 * 날씨 조건별 코디 이미지 30개를 수동으로 생성합니다.
 * @summary 배치 이미지 수동 생성
 */
export type batchControllerTriggerGenerationResponse200 = {
  data: BatchTriggerResponseDto
  status: 200
}

export type batchControllerTriggerGenerationResponse401 = {
  data: BatchControllerTriggerGeneration401
  status: 401
}
    
export type batchControllerTriggerGenerationResponseSuccess = (batchControllerTriggerGenerationResponse200) & {
  headers: Headers;
};
export type batchControllerTriggerGenerationResponseError = (batchControllerTriggerGenerationResponse401) & {
  headers: Headers;
};

export type batchControllerTriggerGenerationResponse = (batchControllerTriggerGenerationResponseSuccess | batchControllerTriggerGenerationResponseError)

export const getBatchControllerTriggerGenerationUrl = () => {


  

  return `/batch/generate`
}

export const batchControllerTriggerGeneration = async ( options?: RequestInit): Promise<batchControllerTriggerGenerationResponse> => {
  
  const res = await fetch(getBatchControllerTriggerGenerationUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: batchControllerTriggerGenerationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as batchControllerTriggerGenerationResponse
}


/**
 * 개발/테스트용. production 환경에서는 사용 불가.
 * @summary [DEV] 배치 이미지 수동 생성 (인증 불필요)
 */
export type batchControllerDevTriggerGenerationResponse200 = {
  data: BatchTriggerResponseDto
  status: 200
}

export type batchControllerDevTriggerGenerationResponse403 = {
  data: BatchControllerDevTriggerGeneration403
  status: 403
}
    
export type batchControllerDevTriggerGenerationResponseSuccess = (batchControllerDevTriggerGenerationResponse200) & {
  headers: Headers;
};
export type batchControllerDevTriggerGenerationResponseError = (batchControllerDevTriggerGenerationResponse403) & {
  headers: Headers;
};

export type batchControllerDevTriggerGenerationResponse = (batchControllerDevTriggerGenerationResponseSuccess | batchControllerDevTriggerGenerationResponseError)

export const getBatchControllerDevTriggerGenerationUrl = () => {


  

  return `/batch/dev/generate`
}

export const batchControllerDevTriggerGeneration = async ( options?: RequestInit): Promise<batchControllerDevTriggerGenerationResponse> => {
  
  const res = await fetch(getBatchControllerDevTriggerGenerationUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: batchControllerDevTriggerGenerationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as batchControllerDevTriggerGenerationResponse
}


