/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  ClothesControllerCreate400,
  ClothesControllerCreate401,
  ClothesControllerEnrich400,
  ClothesControllerEnrich401,
  ClothesControllerFindAll400,
  ClothesControllerFindAll401,
  ClothesControllerFindOne400,
  ClothesControllerFindOne401,
  ClothesControllerFindOne404,
  ClothesControllerRemove400,
  ClothesControllerRemove401,
  ClothesControllerRemove404,
  ClothesControllerSuggest400,
  ClothesControllerUpdate400,
  ClothesControllerUpdate401,
  ClothesControllerUpdate404,
  ClothesDeleteResponseDto,
  ClothesResponseDto,
  ClothesUpdateResponseDto,
  CreateClothesDto,
  EnrichClothesDto,
  EnrichClothesResponseDto,
  SuggestClothesDto,
  UpdateClothesDto
} from '../orvalSchemas';



/**
 * 사용자의 옷장에 새로운 의류를 등록합니다.
 * @summary 의류 등록
 */
export type clothesControllerCreateResponse201 = {
  data: ClothesResponseDto
  status: 201
}

export type clothesControllerCreateResponse400 = {
  data: ClothesControllerCreate400
  status: 400
}

export type clothesControllerCreateResponse401 = {
  data: ClothesControllerCreate401
  status: 401
}
    
export type clothesControllerCreateResponseSuccess = (clothesControllerCreateResponse201) & {
  headers: Headers;
};
export type clothesControllerCreateResponseError = (clothesControllerCreateResponse400 | clothesControllerCreateResponse401) & {
  headers: Headers;
};

export type clothesControllerCreateResponse = (clothesControllerCreateResponseSuccess | clothesControllerCreateResponseError)

export const getClothesControllerCreateUrl = () => {


  

  return `/clothes`
}

export const clothesControllerCreate = async (createClothesDto: CreateClothesDto, options?: RequestInit): Promise<clothesControllerCreateResponse> => {
  
  const res = await fetch(getClothesControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createClothesDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerCreateResponse
}


/**
 * 현재 사용자가 등록한 모든 의류 목록을 가져옵니다.
 * @summary 의류 목록 조회
 */
export type clothesControllerFindAllResponse200 = {
  data: ClothesResponseDto[]
  status: 200
}

export type clothesControllerFindAllResponse400 = {
  data: ClothesControllerFindAll400
  status: 400
}

export type clothesControllerFindAllResponse401 = {
  data: ClothesControllerFindAll401
  status: 401
}
    
export type clothesControllerFindAllResponseSuccess = (clothesControllerFindAllResponse200) & {
  headers: Headers;
};
export type clothesControllerFindAllResponseError = (clothesControllerFindAllResponse400 | clothesControllerFindAllResponse401) & {
  headers: Headers;
};

export type clothesControllerFindAllResponse = (clothesControllerFindAllResponseSuccess | clothesControllerFindAllResponseError)

export const getClothesControllerFindAllUrl = () => {


  

  return `/clothes`
}

export const clothesControllerFindAll = async ( options?: RequestInit): Promise<clothesControllerFindAllResponse> => {
  
  const res = await fetch(getClothesControllerFindAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerFindAllResponse
}


/**
 * 특정 의류의 상세 정보를 조회합니다.
 * @summary 의류 상세 조회
 */
export type clothesControllerFindOneResponse200 = {
  data: ClothesResponseDto
  status: 200
}

export type clothesControllerFindOneResponse400 = {
  data: ClothesControllerFindOne400
  status: 400
}

export type clothesControllerFindOneResponse401 = {
  data: ClothesControllerFindOne401
  status: 401
}

export type clothesControllerFindOneResponse404 = {
  data: ClothesControllerFindOne404
  status: 404
}
    
export type clothesControllerFindOneResponseSuccess = (clothesControllerFindOneResponse200) & {
  headers: Headers;
};
export type clothesControllerFindOneResponseError = (clothesControllerFindOneResponse400 | clothesControllerFindOneResponse401 | clothesControllerFindOneResponse404) & {
  headers: Headers;
};

export type clothesControllerFindOneResponse = (clothesControllerFindOneResponseSuccess | clothesControllerFindOneResponseError)

export const getClothesControllerFindOneUrl = (id: string,) => {


  

  return `/clothes/${id}`
}

export const clothesControllerFindOne = async (id: string, options?: RequestInit): Promise<clothesControllerFindOneResponse> => {
  
  const res = await fetch(getClothesControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerFindOneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerFindOneResponse
}


/**
 * 등록된 의류의 메타데이터를 수정합니다.
 * @summary 의류 정보 수정
 */
export type clothesControllerUpdateResponse200 = {
  data: ClothesUpdateResponseDto
  status: 200
}

export type clothesControllerUpdateResponse400 = {
  data: ClothesControllerUpdate400
  status: 400
}

export type clothesControllerUpdateResponse401 = {
  data: ClothesControllerUpdate401
  status: 401
}

export type clothesControllerUpdateResponse404 = {
  data: ClothesControllerUpdate404
  status: 404
}
    
export type clothesControllerUpdateResponseSuccess = (clothesControllerUpdateResponse200) & {
  headers: Headers;
};
export type clothesControllerUpdateResponseError = (clothesControllerUpdateResponse400 | clothesControllerUpdateResponse401 | clothesControllerUpdateResponse404) & {
  headers: Headers;
};

export type clothesControllerUpdateResponse = (clothesControllerUpdateResponseSuccess | clothesControllerUpdateResponseError)

export const getClothesControllerUpdateUrl = (id: string,) => {


  

  return `/clothes/${id}`
}

export const clothesControllerUpdate = async (id: string,
    updateClothesDto: UpdateClothesDto, options?: RequestInit): Promise<clothesControllerUpdateResponse> => {
  
  const res = await fetch(getClothesControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateClothesDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerUpdateResponse
}


/**
 * 등록된 의류를 삭제(Soft Delete)합니다.
 * @summary 의류 삭제
 */
export type clothesControllerRemoveResponse200 = {
  data: ClothesDeleteResponseDto
  status: 200
}

export type clothesControllerRemoveResponse400 = {
  data: ClothesControllerRemove400
  status: 400
}

export type clothesControllerRemoveResponse401 = {
  data: ClothesControllerRemove401
  status: 401
}

export type clothesControllerRemoveResponse404 = {
  data: ClothesControllerRemove404
  status: 404
}
    
export type clothesControllerRemoveResponseSuccess = (clothesControllerRemoveResponse200) & {
  headers: Headers;
};
export type clothesControllerRemoveResponseError = (clothesControllerRemoveResponse400 | clothesControllerRemoveResponse401 | clothesControllerRemoveResponse404) & {
  headers: Headers;
};

export type clothesControllerRemoveResponse = (clothesControllerRemoveResponseSuccess | clothesControllerRemoveResponseError)

export const getClothesControllerRemoveUrl = (id: string,) => {


  

  return `/clothes/${id}`
}

export const clothesControllerRemove = async (id: string, options?: RequestInit): Promise<clothesControllerRemoveResponse> => {
  
  const res = await fetch(getClothesControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerRemoveResponse
}


/**
 * AI를 사용하여 의류 이미지에서 속성(색상, 카테고리 등)을 추출합니다. Supabase Storage URL을 전달하세요.
 * @summary 의류 이미지 분석
 */
export type clothesControllerEnrichResponse200 = {
  data: EnrichClothesResponseDto
  status: 200
}

export type clothesControllerEnrichResponse400 = {
  data: ClothesControllerEnrich400
  status: 400
}

export type clothesControllerEnrichResponse401 = {
  data: ClothesControllerEnrich401
  status: 401
}
    
export type clothesControllerEnrichResponseSuccess = (clothesControllerEnrichResponse200) & {
  headers: Headers;
};
export type clothesControllerEnrichResponseError = (clothesControllerEnrichResponse400 | clothesControllerEnrichResponse401) & {
  headers: Headers;
};

export type clothesControllerEnrichResponse = (clothesControllerEnrichResponseSuccess | clothesControllerEnrichResponseError)

export const getClothesControllerEnrichUrl = () => {


  

  return `/clothes/enrich`
}

export const clothesControllerEnrich = async (enrichClothesDto: EnrichClothesDto, options?: RequestInit): Promise<clothesControllerEnrichResponse> => {
  
  const res = await fetch(getClothesControllerEnrichUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      enrichClothesDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerEnrichResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerEnrichResponse
}


/**
 * ⚠️ 현재 미지원 기능입니다. 이미지 URL과 텍스트를 기반으로 AI가 새로운 의류를 제안하거나 이미지를 생성합니다.
 * @deprecated
 * @summary AI 의류 제안 및 생성 (미지원)
 */
export type clothesControllerSuggestResponse200 = {
  data: unknown
  status: 200
}

export type clothesControllerSuggestResponse400 = {
  data: ClothesControllerSuggest400
  status: 400
}

export type clothesControllerSuggestResponse501 = {
  data: unknown
  status: 501
}
    
export type clothesControllerSuggestResponseSuccess = (clothesControllerSuggestResponse200) & {
  headers: Headers;
};
export type clothesControllerSuggestResponseError = (clothesControllerSuggestResponse400 | clothesControllerSuggestResponse501) & {
  headers: Headers;
};

export type clothesControllerSuggestResponse = (clothesControllerSuggestResponseSuccess | clothesControllerSuggestResponseError)

export const getClothesControllerSuggestUrl = () => {


  

  return `/clothes/suggest`
}

export const clothesControllerSuggest = async (suggestClothesDto: SuggestClothesDto, options?: RequestInit): Promise<clothesControllerSuggestResponse> => {
  
  const res = await fetch(getClothesControllerSuggestUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      suggestClothesDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerSuggestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerSuggestResponse
}


