/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  ClothesCommitResponseDto,
  ClothesControllerCreate400,
  ClothesControllerCreate401,
  ClothesControllerCreateBackgroundRemovalPreview400,
  ClothesControllerCreateBackgroundRemovalPreview401,
  ClothesControllerEnrich400,
  ClothesControllerEnrich401,
  ClothesControllerFavorite400,
  ClothesControllerFavorite401,
  ClothesControllerFavorite404,
  ClothesControllerFindAll400,
  ClothesControllerFindAll401,
  ClothesControllerFindAllParams,
  ClothesControllerFindOne400,
  ClothesControllerFindOne401,
  ClothesControllerFindOne404,
  ClothesControllerFindOneParams,
  ClothesControllerGetClothesImage400,
  ClothesControllerGetClothesImage401,
  ClothesControllerGetClothesImage404,
  ClothesControllerGetClothesImageParams,
  ClothesControllerRemove400,
  ClothesControllerRemove401,
  ClothesControllerRemove404,
  ClothesControllerSuggest400,
  ClothesControllerUnfavorite400,
  ClothesControllerUnfavorite401,
  ClothesControllerUnfavorite404,
  ClothesControllerUpdate400,
  ClothesControllerUpdate401,
  ClothesControllerUpdate404,
  ClothesDeleteResponseDto,
  ClothesFavoriteResponseDto,
  ClothesImagePreviewRequestDto,
  ClothesListItemResponseDto,
  ClothesPreviewResponseDto,
  ClothesResponseDto,
  ClothesUpdateResponseDto,
  CreateClothesDto,
  EnrichClothesDto,
  EnrichClothesResponseDto,
  SuggestClothesDto,
  UpdateClothesDto
} from '../orvalSchemas';



/**
 * 사용자의 옷장에 새로운 의류를 등록합니다.
 * @summary 의류 등록
 */
export type clothesControllerCreateResponse201 = {
  data: ClothesResponseDto
  status: 201
}

export type clothesControllerCreateResponse400 = {
  data: ClothesControllerCreate400
  status: 400
}

export type clothesControllerCreateResponse401 = {
  data: ClothesControllerCreate401
  status: 401
}
    
export type clothesControllerCreateResponseSuccess = (clothesControllerCreateResponse201) & {
  headers: Headers;
};
export type clothesControllerCreateResponseError = (clothesControllerCreateResponse400 | clothesControllerCreateResponse401) & {
  headers: Headers;
};

export type clothesControllerCreateResponse = (clothesControllerCreateResponseSuccess | clothesControllerCreateResponseError)

export const getClothesControllerCreateUrl = () => {


  

  return `/clothes`
}

export const clothesControllerCreate = async (createClothesDto: CreateClothesDto, options?: RequestInit): Promise<clothesControllerCreateResponse> => {
  
  const res = await fetch(getClothesControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createClothesDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerCreateResponse
}


/**
 * 현재 사용자가 등록한 모든 의류 목록을 가져옵니다.
 * @summary 의류 목록 조회
 */
export type clothesControllerFindAllResponse200 = {
  data: ClothesListItemResponseDto[]
  status: 200
}

export type clothesControllerFindAllResponse400 = {
  data: ClothesControllerFindAll400
  status: 400
}

export type clothesControllerFindAllResponse401 = {
  data: ClothesControllerFindAll401
  status: 401
}
    
export type clothesControllerFindAllResponseSuccess = (clothesControllerFindAllResponse200) & {
  headers: Headers;
};
export type clothesControllerFindAllResponseError = (clothesControllerFindAllResponse400 | clothesControllerFindAllResponse401) & {
  headers: Headers;
};

export type clothesControllerFindAllResponse = (clothesControllerFindAllResponseSuccess | clothesControllerFindAllResponseError)

export const getClothesControllerFindAllUrl = (params?: ClothesControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/clothes?${stringifiedParams}` : `/clothes`
}

export const clothesControllerFindAll = async (params?: ClothesControllerFindAllParams, options?: RequestInit): Promise<clothesControllerFindAllResponse> => {
  
  const res = await fetch(getClothesControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerFindAllResponse
}


/**
 * 특정 의류의 상세 정보를 조회합니다.
 * @summary 의류 상세 조회
 */
export type clothesControllerFindOneResponse200 = {
  data: ClothesResponseDto
  status: 200
}

export type clothesControllerFindOneResponse400 = {
  data: ClothesControllerFindOne400
  status: 400
}

export type clothesControllerFindOneResponse401 = {
  data: ClothesControllerFindOne401
  status: 401
}

export type clothesControllerFindOneResponse404 = {
  data: ClothesControllerFindOne404
  status: 404
}
    
export type clothesControllerFindOneResponseSuccess = (clothesControllerFindOneResponse200) & {
  headers: Headers;
};
export type clothesControllerFindOneResponseError = (clothesControllerFindOneResponse400 | clothesControllerFindOneResponse401 | clothesControllerFindOneResponse404) & {
  headers: Headers;
};

export type clothesControllerFindOneResponse = (clothesControllerFindOneResponseSuccess | clothesControllerFindOneResponseError)

export const getClothesControllerFindOneUrl = (id: string,
    params?: ClothesControllerFindOneParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/clothes/${id}?${stringifiedParams}` : `/clothes/${id}`
}

export const clothesControllerFindOne = async (id: string,
    params?: ClothesControllerFindOneParams, options?: RequestInit): Promise<clothesControllerFindOneResponse> => {
  
  const res = await fetch(getClothesControllerFindOneUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerFindOneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerFindOneResponse
}


/**
 * 등록된 의류의 메타데이터를 수정합니다.
 * @summary 의류 정보 수정
 */
export type clothesControllerUpdateResponse200 = {
  data: ClothesUpdateResponseDto
  status: 200
}

export type clothesControllerUpdateResponse400 = {
  data: ClothesControllerUpdate400
  status: 400
}

export type clothesControllerUpdateResponse401 = {
  data: ClothesControllerUpdate401
  status: 401
}

export type clothesControllerUpdateResponse404 = {
  data: ClothesControllerUpdate404
  status: 404
}
    
export type clothesControllerUpdateResponseSuccess = (clothesControllerUpdateResponse200) & {
  headers: Headers;
};
export type clothesControllerUpdateResponseError = (clothesControllerUpdateResponse400 | clothesControllerUpdateResponse401 | clothesControllerUpdateResponse404) & {
  headers: Headers;
};

export type clothesControllerUpdateResponse = (clothesControllerUpdateResponseSuccess | clothesControllerUpdateResponseError)

export const getClothesControllerUpdateUrl = (id: string,) => {


  

  return `/clothes/${id}`
}

export const clothesControllerUpdate = async (id: string,
    updateClothesDto: UpdateClothesDto, options?: RequestInit): Promise<clothesControllerUpdateResponse> => {
  
  const res = await fetch(getClothesControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateClothesDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerUpdateResponse
}


/**
 * 등록된 의류를 삭제(Soft Delete)합니다.
 * @summary 의류 삭제
 */
export type clothesControllerRemoveResponse200 = {
  data: ClothesDeleteResponseDto
  status: 200
}

export type clothesControllerRemoveResponse400 = {
  data: ClothesControllerRemove400
  status: 400
}

export type clothesControllerRemoveResponse401 = {
  data: ClothesControllerRemove401
  status: 401
}

export type clothesControllerRemoveResponse404 = {
  data: ClothesControllerRemove404
  status: 404
}
    
export type clothesControllerRemoveResponseSuccess = (clothesControllerRemoveResponse200) & {
  headers: Headers;
};
export type clothesControllerRemoveResponseError = (clothesControllerRemoveResponse400 | clothesControllerRemoveResponse401 | clothesControllerRemoveResponse404) & {
  headers: Headers;
};

export type clothesControllerRemoveResponse = (clothesControllerRemoveResponseSuccess | clothesControllerRemoveResponseError)

export const getClothesControllerRemoveUrl = (id: string,) => {


  

  return `/clothes/${id}`
}

export const clothesControllerRemove = async (id: string, options?: RequestInit): Promise<clothesControllerRemoveResponse> => {
  
  const res = await fetch(getClothesControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerRemoveResponse
}


/**
 * 해당 의류를 즐겨찾기 상태로 설정합니다.
 * @summary 의류 즐겨찾기 등록
 */
export type clothesControllerFavoriteResponse200 = {
  data: ClothesFavoriteResponseDto
  status: 200
}

export type clothesControllerFavoriteResponse400 = {
  data: ClothesControllerFavorite400
  status: 400
}

export type clothesControllerFavoriteResponse401 = {
  data: ClothesControllerFavorite401
  status: 401
}

export type clothesControllerFavoriteResponse404 = {
  data: ClothesControllerFavorite404
  status: 404
}
    
export type clothesControllerFavoriteResponseSuccess = (clothesControllerFavoriteResponse200) & {
  headers: Headers;
};
export type clothesControllerFavoriteResponseError = (clothesControllerFavoriteResponse400 | clothesControllerFavoriteResponse401 | clothesControllerFavoriteResponse404) & {
  headers: Headers;
};

export type clothesControllerFavoriteResponse = (clothesControllerFavoriteResponseSuccess | clothesControllerFavoriteResponseError)

export const getClothesControllerFavoriteUrl = (id: string,) => {


  

  return `/clothes/${id}/favorite`
}

export const clothesControllerFavorite = async (id: string, options?: RequestInit): Promise<clothesControllerFavoriteResponse> => {
  
  const res = await fetch(getClothesControllerFavoriteUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerFavoriteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerFavoriteResponse
}


/**
 * 해당 의류의 즐겨찾기 상태를 해제합니다.
 * @summary 의류 즐겨찾기 해제
 */
export type clothesControllerUnfavoriteResponse200 = {
  data: ClothesFavoriteResponseDto
  status: 200
}

export type clothesControllerUnfavoriteResponse400 = {
  data: ClothesControllerUnfavorite400
  status: 400
}

export type clothesControllerUnfavoriteResponse401 = {
  data: ClothesControllerUnfavorite401
  status: 401
}

export type clothesControllerUnfavoriteResponse404 = {
  data: ClothesControllerUnfavorite404
  status: 404
}
    
export type clothesControllerUnfavoriteResponseSuccess = (clothesControllerUnfavoriteResponse200) & {
  headers: Headers;
};
export type clothesControllerUnfavoriteResponseError = (clothesControllerUnfavoriteResponse400 | clothesControllerUnfavoriteResponse401 | clothesControllerUnfavoriteResponse404) & {
  headers: Headers;
};

export type clothesControllerUnfavoriteResponse = (clothesControllerUnfavoriteResponseSuccess | clothesControllerUnfavoriteResponseError)

export const getClothesControllerUnfavoriteUrl = (id: string,) => {


  

  return `/clothes/${id}/favorite`
}

export const clothesControllerUnfavorite = async (id: string, options?: RequestInit): Promise<clothesControllerUnfavoriteResponse> => {
  
  const res = await fetch(getClothesControllerUnfavoriteUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerUnfavoriteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerUnfavoriteResponse
}


/**
 * AI를 사용하여 의류 이미지에서 속성(색상, 카테고리 등)을 추출합니다. Supabase Storage URL을 전달하세요.
 * @summary 의류 이미지 분석
 */
export type clothesControllerEnrichResponse200 = {
  data: EnrichClothesResponseDto
  status: 200
}

export type clothesControllerEnrichResponse400 = {
  data: ClothesControllerEnrich400
  status: 400
}

export type clothesControllerEnrichResponse401 = {
  data: ClothesControllerEnrich401
  status: 401
}
    
export type clothesControllerEnrichResponseSuccess = (clothesControllerEnrichResponse200) & {
  headers: Headers;
};
export type clothesControllerEnrichResponseError = (clothesControllerEnrichResponse400 | clothesControllerEnrichResponse401) & {
  headers: Headers;
};

export type clothesControllerEnrichResponse = (clothesControllerEnrichResponseSuccess | clothesControllerEnrichResponseError)

export const getClothesControllerEnrichUrl = () => {


  

  return `/clothes/enrich`
}

export const clothesControllerEnrich = async (enrichClothesDto: EnrichClothesDto, options?: RequestInit): Promise<clothesControllerEnrichResponse> => {
  
  const res = await fetch(getClothesControllerEnrichUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      enrichClothesDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerEnrichResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerEnrichResponse
}


/**
 * ⚠️ 현재 미지원 기능입니다. 이미지 URL과 텍스트를 기반으로 AI가 새로운 의류를 제안하거나 이미지를 생성합니다.
 * @deprecated
 * @summary AI 의류 제안 및 생성 (미지원)
 */
export type clothesControllerSuggestResponse200 = {
  data: unknown
  status: 200
}

export type clothesControllerSuggestResponse400 = {
  data: ClothesControllerSuggest400
  status: 400
}

export type clothesControllerSuggestResponse501 = {
  data: unknown
  status: 501
}
    
export type clothesControllerSuggestResponseSuccess = (clothesControllerSuggestResponse200) & {
  headers: Headers;
};
export type clothesControllerSuggestResponseError = (clothesControllerSuggestResponse400 | clothesControllerSuggestResponse501) & {
  headers: Headers;
};

export type clothesControllerSuggestResponse = (clothesControllerSuggestResponseSuccess | clothesControllerSuggestResponseError)

export const getClothesControllerSuggestUrl = () => {


  

  return `/clothes/suggest`
}

export const clothesControllerSuggest = async (suggestClothesDto: SuggestClothesDto, options?: RequestInit): Promise<clothesControllerSuggestResponse> => {
  
  const res = await fetch(getClothesControllerSuggestUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      suggestClothesDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerSuggestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerSuggestResponse
}


/**
 * 원본 이미지를 기준으로 배경제거를 수행하고 미리보기 URL을 반환합니다.
 * @summary 의류 이미지 배경제거 미리보기 생성
 */
export type clothesControllerCreateBackgroundRemovalPreviewResponse200 = {
  data: ClothesPreviewResponseDto
  status: 200
}

export type clothesControllerCreateBackgroundRemovalPreviewResponse400 = {
  data: ClothesControllerCreateBackgroundRemovalPreview400
  status: 400
}

export type clothesControllerCreateBackgroundRemovalPreviewResponse401 = {
  data: ClothesControllerCreateBackgroundRemovalPreview401
  status: 401
}
    
export type clothesControllerCreateBackgroundRemovalPreviewResponseSuccess = (clothesControllerCreateBackgroundRemovalPreviewResponse200) & {
  headers: Headers;
};
export type clothesControllerCreateBackgroundRemovalPreviewResponseError = (clothesControllerCreateBackgroundRemovalPreviewResponse400 | clothesControllerCreateBackgroundRemovalPreviewResponse401) & {
  headers: Headers;
};

export type clothesControllerCreateBackgroundRemovalPreviewResponse = (clothesControllerCreateBackgroundRemovalPreviewResponseSuccess | clothesControllerCreateBackgroundRemovalPreviewResponseError)

export const getClothesControllerCreateBackgroundRemovalPreviewUrl = () => {


  

  return `/clothes/images/preview`
}

export const clothesControllerCreateBackgroundRemovalPreview = async (clothesImagePreviewRequestDto: ClothesImagePreviewRequestDto, options?: RequestInit): Promise<clothesControllerCreateBackgroundRemovalPreviewResponse> => {
    const formData = new FormData();
formData.append(`file`, clothesImagePreviewRequestDto.file);

  const res = await fetch(getClothesControllerCreateBackgroundRemovalPreviewUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerCreateBackgroundRemovalPreviewResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerCreateBackgroundRemovalPreviewResponse
}


/**
 * 저장된 의류 이미지 파생본(detail/card/thumb)의 signed URL을 조회합니다.
 * @summary 의류 이미지 파생본 조회
 */
export type clothesControllerGetClothesImageResponse200 = {
  data: ClothesCommitResponseDto
  status: 200
}

export type clothesControllerGetClothesImageResponse400 = {
  data: ClothesControllerGetClothesImage400
  status: 400
}

export type clothesControllerGetClothesImageResponse401 = {
  data: ClothesControllerGetClothesImage401
  status: 401
}

export type clothesControllerGetClothesImageResponse404 = {
  data: ClothesControllerGetClothesImage404
  status: 404
}
    
export type clothesControllerGetClothesImageResponseSuccess = (clothesControllerGetClothesImageResponse200) & {
  headers: Headers;
};
export type clothesControllerGetClothesImageResponseError = (clothesControllerGetClothesImageResponse400 | clothesControllerGetClothesImageResponse401 | clothesControllerGetClothesImageResponse404) & {
  headers: Headers;
};

export type clothesControllerGetClothesImageResponse = (clothesControllerGetClothesImageResponseSuccess | clothesControllerGetClothesImageResponseError)

export const getClothesControllerGetClothesImageUrl = (clothesId: string,
    params?: ClothesControllerGetClothesImageParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/clothes/${clothesId}/images?${stringifiedParams}` : `/clothes/${clothesId}/images`
}

export const clothesControllerGetClothesImage = async (clothesId: string,
    params?: ClothesControllerGetClothesImageParams, options?: RequestInit): Promise<clothesControllerGetClothesImageResponse> => {
  
  const res = await fetch(getClothesControllerGetClothesImageUrl(clothesId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clothesControllerGetClothesImageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clothesControllerGetClothesImageResponse
}


