/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  CommentDeleteResponseDto,
  CommentResponseDto,
  CommentsControllerCreate400,
  CommentsControllerCreate401,
  CommentsControllerCreate404,
  CommentsControllerFindAll400,
  CommentsControllerFindAll404,
  CommentsControllerRemove400,
  CommentsControllerRemove401,
  CommentsControllerRemove404,
  CreateCommentDto
} from '../orvalSchemas';



/**
 * 공유된 룩에 댓글 또는 대댓글을 작성합니다.
 * @summary 댓글 작성
 */
export type commentsControllerCreateResponse201 = {
  data: CommentResponseDto
  status: 201
}

export type commentsControllerCreateResponse400 = {
  data: CommentsControllerCreate400
  status: 400
}

export type commentsControllerCreateResponse401 = {
  data: CommentsControllerCreate401
  status: 401
}

export type commentsControllerCreateResponse404 = {
  data: CommentsControllerCreate404
  status: 404
}
    
export type commentsControllerCreateResponseSuccess = (commentsControllerCreateResponse201) & {
  headers: Headers;
};
export type commentsControllerCreateResponseError = (commentsControllerCreateResponse400 | commentsControllerCreateResponse401 | commentsControllerCreateResponse404) & {
  headers: Headers;
};

export type commentsControllerCreateResponse = (commentsControllerCreateResponseSuccess | commentsControllerCreateResponseError)

export const getCommentsControllerCreateUrl = (path: string,) => {


  

  return `/shares/${path}/comments`
}

export const commentsControllerCreate = async (path: string,
    createCommentDto: CreateCommentDto, options?: RequestInit): Promise<commentsControllerCreateResponse> => {
  
  const res = await fetch(getCommentsControllerCreateUrl(path),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCommentDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: commentsControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commentsControllerCreateResponse
}


/**
 * 공유된 룩의 모든 댓글 목록을 가져옵니다.
 * @summary 댓글 목록 조회
 */
export type commentsControllerFindAllResponse200 = {
  data: CommentResponseDto[]
  status: 200
}

export type commentsControllerFindAllResponse400 = {
  data: CommentsControllerFindAll400
  status: 400
}

export type commentsControllerFindAllResponse404 = {
  data: CommentsControllerFindAll404
  status: 404
}
    
export type commentsControllerFindAllResponseSuccess = (commentsControllerFindAllResponse200) & {
  headers: Headers;
};
export type commentsControllerFindAllResponseError = (commentsControllerFindAllResponse400 | commentsControllerFindAllResponse404) & {
  headers: Headers;
};

export type commentsControllerFindAllResponse = (commentsControllerFindAllResponseSuccess | commentsControllerFindAllResponseError)

export const getCommentsControllerFindAllUrl = (path: string,) => {


  

  return `/shares/${path}/comments`
}

export const commentsControllerFindAll = async (path: string, options?: RequestInit): Promise<commentsControllerFindAllResponse> => {
  
  const res = await fetch(getCommentsControllerFindAllUrl(path),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: commentsControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commentsControllerFindAllResponse
}


/**
 * 작성한 댓글을 삭제합니다.
 * @summary 댓글 삭제
 */
export type commentsControllerRemoveResponse200 = {
  data: CommentDeleteResponseDto
  status: 200
}

export type commentsControllerRemoveResponse400 = {
  data: CommentsControllerRemove400
  status: 400
}

export type commentsControllerRemoveResponse401 = {
  data: CommentsControllerRemove401
  status: 401
}

export type commentsControllerRemoveResponse404 = {
  data: CommentsControllerRemove404
  status: 404
}
    
export type commentsControllerRemoveResponseSuccess = (commentsControllerRemoveResponse200) & {
  headers: Headers;
};
export type commentsControllerRemoveResponseError = (commentsControllerRemoveResponse400 | commentsControllerRemoveResponse401 | commentsControllerRemoveResponse404) & {
  headers: Headers;
};

export type commentsControllerRemoveResponse = (commentsControllerRemoveResponseSuccess | commentsControllerRemoveResponseError)

export const getCommentsControllerRemoveUrl = (path: string,
    id: string,) => {


  

  return `/shares/${path}/comments/${id}`
}

export const commentsControllerRemove = async (path: string,
    id: string, options?: RequestInit): Promise<commentsControllerRemoveResponse> => {
  
  const res = await fetch(getCommentsControllerRemoveUrl(path,id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: commentsControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commentsControllerRemoveResponse
}


