/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  HealthControllerCheckReady400,
  HealthStatusDto,
  LlmHealthControllerCheckModels400,
  LlmHealthResponseDto
} from '../orvalSchemas';



/**
 * DB 및 스토리지 연결 상태를 확인합니다.
 * @summary 서버 상태 확인
 */
export type healthControllerCheckReadyResponse200 = {
  data: HealthStatusDto
  status: 200
}

export type healthControllerCheckReadyResponse400 = {
  data: HealthControllerCheckReady400
  status: 400
}

export type healthControllerCheckReadyResponse503 = {
  data: HealthStatusDto
  status: 503
}
    
export type healthControllerCheckReadyResponseSuccess = (healthControllerCheckReadyResponse200) & {
  headers: Headers;
};
export type healthControllerCheckReadyResponseError = (healthControllerCheckReadyResponse400 | healthControllerCheckReadyResponse503) & {
  headers: Headers;
};

export type healthControllerCheckReadyResponse = (healthControllerCheckReadyResponseSuccess | healthControllerCheckReadyResponseError)

export const getHealthControllerCheckReadyUrl = () => {


  

  return `/health`
}

export const healthControllerCheckReady = async ( options?: RequestInit): Promise<healthControllerCheckReadyResponse> => {
  
  const res = await fetch(getHealthControllerCheckReadyUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: healthControllerCheckReadyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthControllerCheckReadyResponse
}


/**
 * 모델 목록 조회를 통해 LLM 접근 가능 여부를 확인합니다.
 * @summary LLM 모델 상태 확인
 */
export type llmHealthControllerCheckModelsResponse200 = {
  data: LlmHealthResponseDto
  status: 200
}

export type llmHealthControllerCheckModelsResponse400 = {
  data: LlmHealthControllerCheckModels400
  status: 400
}

export type llmHealthControllerCheckModelsResponse503 = {
  data: LlmHealthResponseDto
  status: 503
}
    
export type llmHealthControllerCheckModelsResponseSuccess = (llmHealthControllerCheckModelsResponse200) & {
  headers: Headers;
};
export type llmHealthControllerCheckModelsResponseError = (llmHealthControllerCheckModelsResponse400 | llmHealthControllerCheckModelsResponse503) & {
  headers: Headers;
};

export type llmHealthControllerCheckModelsResponse = (llmHealthControllerCheckModelsResponseSuccess | llmHealthControllerCheckModelsResponseError)

export const getLlmHealthControllerCheckModelsUrl = () => {


  

  return `/health/llm`
}

export const llmHealthControllerCheckModels = async ( options?: RequestInit): Promise<llmHealthControllerCheckModelsResponse> => {
  
  const res = await fetch(getLlmHealthControllerCheckModelsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: llmHealthControllerCheckModelsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as llmHealthControllerCheckModelsResponse
}


