/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  CreateLocationDto,
  LocationDto,
  LocationsControllerCreate400,
  LocationsControllerCreate401,
  LocationsControllerFindAll400,
  LocationsControllerGetWeather400,
  LocationsControllerGetWeather404,
  LocationsControllerRemove400,
  LocationsControllerRemove401,
  LocationsControllerRemove404,
  LocationsControllerUpdate400,
  LocationsControllerUpdate401,
  LocationsControllerUpdate404,
  UpdateLocationDto,
  UserLocationDeleteResponseDto,
  UserLocationResponseDto,
  WeatherResponseDto
} from '../orvalSchemas';



/**
 * 사용자의 주요 위치(위경도 기반)를 등록합니다.
 * @summary 위치 등록
 */
export type locationsControllerCreateResponse201 = {
  data: UserLocationResponseDto
  status: 201
}

export type locationsControllerCreateResponse400 = {
  data: LocationsControllerCreate400
  status: 400
}

export type locationsControllerCreateResponse401 = {
  data: LocationsControllerCreate401
  status: 401
}
    
export type locationsControllerCreateResponseSuccess = (locationsControllerCreateResponse201) & {
  headers: Headers;
};
export type locationsControllerCreateResponseError = (locationsControllerCreateResponse400 | locationsControllerCreateResponse401) & {
  headers: Headers;
};

export type locationsControllerCreateResponse = (locationsControllerCreateResponseSuccess | locationsControllerCreateResponseError)

export const getLocationsControllerCreateUrl = () => {


  

  return `/locations`
}

export const locationsControllerCreate = async (createLocationDto: CreateLocationDto, options?: RequestInit): Promise<locationsControllerCreateResponse> => {
  
  const res = await fetch(getLocationsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createLocationDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: locationsControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as locationsControllerCreateResponse
}


/**
 * 인증 시 사용자가 등록한 모든 위치 목록을 반환합니다. 인증 없이 호출 시 기본 지역 정보 하나를 반환합니다.
 * @summary 위치 목록 조회
 */
export type locationsControllerFindAllResponse200 = {
  data: UserLocationResponseDto[] | LocationDto
  status: 200
}

export type locationsControllerFindAllResponse400 = {
  data: LocationsControllerFindAll400
  status: 400
}
    
export type locationsControllerFindAllResponseSuccess = (locationsControllerFindAllResponse200) & {
  headers: Headers;
};
export type locationsControllerFindAllResponseError = (locationsControllerFindAllResponse400) & {
  headers: Headers;
};

export type locationsControllerFindAllResponse = (locationsControllerFindAllResponseSuccess | locationsControllerFindAllResponseError)

export const getLocationsControllerFindAllUrl = () => {


  

  return `/locations`
}

export const locationsControllerFindAll = async ( options?: RequestInit): Promise<locationsControllerFindAllResponse> => {
  
  const res = await fetch(getLocationsControllerFindAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: locationsControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as locationsControllerFindAllResponse
}


/**
 * 위치의 별칭이나 기본 설정 여부를 수정합니다.
 * @summary 위치 정보 수정
 */
export type locationsControllerUpdateResponse200 = {
  data: UserLocationResponseDto
  status: 200
}

export type locationsControllerUpdateResponse400 = {
  data: LocationsControllerUpdate400
  status: 400
}

export type locationsControllerUpdateResponse401 = {
  data: LocationsControllerUpdate401
  status: 401
}

export type locationsControllerUpdateResponse404 = {
  data: LocationsControllerUpdate404
  status: 404
}
    
export type locationsControllerUpdateResponseSuccess = (locationsControllerUpdateResponse200) & {
  headers: Headers;
};
export type locationsControllerUpdateResponseError = (locationsControllerUpdateResponse400 | locationsControllerUpdateResponse401 | locationsControllerUpdateResponse404) & {
  headers: Headers;
};

export type locationsControllerUpdateResponse = (locationsControllerUpdateResponseSuccess | locationsControllerUpdateResponseError)

export const getLocationsControllerUpdateUrl = (id: string,) => {


  

  return `/locations/${id}`
}

export const locationsControllerUpdate = async (id: string,
    updateLocationDto: UpdateLocationDto, options?: RequestInit): Promise<locationsControllerUpdateResponse> => {
  
  const res = await fetch(getLocationsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateLocationDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: locationsControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as locationsControllerUpdateResponse
}


/**
 * 사용자의 위치 정보를 삭제합니다.
 * @summary 위치 삭제
 */
export type locationsControllerRemoveResponse200 = {
  data: UserLocationDeleteResponseDto
  status: 200
}

export type locationsControllerRemoveResponse400 = {
  data: LocationsControllerRemove400
  status: 400
}

export type locationsControllerRemoveResponse401 = {
  data: LocationsControllerRemove401
  status: 401
}

export type locationsControllerRemoveResponse404 = {
  data: LocationsControllerRemove404
  status: 404
}
    
export type locationsControllerRemoveResponseSuccess = (locationsControllerRemoveResponse200) & {
  headers: Headers;
};
export type locationsControllerRemoveResponseError = (locationsControllerRemoveResponse400 | locationsControllerRemoveResponse401 | locationsControllerRemoveResponse404) & {
  headers: Headers;
};

export type locationsControllerRemoveResponse = (locationsControllerRemoveResponseSuccess | locationsControllerRemoveResponseError)

export const getLocationsControllerRemoveUrl = (id: string,) => {


  

  return `/locations/${id}`
}

export const locationsControllerRemove = async (id: string, options?: RequestInit): Promise<locationsControllerRemoveResponse> => {
  
  const res = await fetch(getLocationsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: locationsControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as locationsControllerRemoveResponse
}


/**
 * 지역 ID 기반으로 최신 날씨 정보를 가져옵니다. (인메모리 → Redis → 기상청 API 3단계 캐싱)
 * @summary 지역별 실시간 날씨 조회
 */
export type locationsControllerGetWeatherResponse200 = {
  data: WeatherResponseDto
  status: 200
}

export type locationsControllerGetWeatherResponse400 = {
  data: LocationsControllerGetWeather400
  status: 400
}

export type locationsControllerGetWeatherResponse404 = {
  data: LocationsControllerGetWeather404
  status: 404
}
    
export type locationsControllerGetWeatherResponseSuccess = (locationsControllerGetWeatherResponse200) & {
  headers: Headers;
};
export type locationsControllerGetWeatherResponseError = (locationsControllerGetWeatherResponse400 | locationsControllerGetWeatherResponse404) & {
  headers: Headers;
};

export type locationsControllerGetWeatherResponse = (locationsControllerGetWeatherResponseSuccess | locationsControllerGetWeatherResponseError)

export const getLocationsControllerGetWeatherUrl = (id: string,) => {


  

  return `/locations/${id}/weather`
}

export const locationsControllerGetWeather = async (id: string, options?: RequestInit): Promise<locationsControllerGetWeatherResponse> => {
  
  const res = await fetch(getLocationsControllerGetWeatherUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: locationsControllerGetWeatherResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as locationsControllerGetWeatherResponse
}


