/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  CreateLookDto,
  LookDeleteResponseDto,
  LookFavoriteResponseDto,
  LookResponseDto,
  LooksControllerCreate400,
  LooksControllerCreate401,
  LooksControllerFavorite400,
  LooksControllerFavorite401,
  LooksControllerFavorite404,
  LooksControllerFindAll400,
  LooksControllerFindAll401,
  LooksControllerFindOne400,
  LooksControllerFindOne401,
  LooksControllerFindOne404,
  LooksControllerRemove400,
  LooksControllerRemove401,
  LooksControllerRemove404,
  LooksControllerUnfavorite400,
  LooksControllerUnfavorite401,
  LooksControllerUnfavorite404,
  LooksControllerUpdate400,
  LooksControllerUpdate401,
  LooksControllerUpdate404,
  UpdateLookDto
} from '../orvalSchemas';



/**
 * 의류들을 조합하여 새로운 룩을 생성합니다.
 * @summary 룩 생성
 */
export type looksControllerCreateResponse201 = {
  data: LookResponseDto
  status: 201
}

export type looksControllerCreateResponse400 = {
  data: LooksControllerCreate400
  status: 400
}

export type looksControllerCreateResponse401 = {
  data: LooksControllerCreate401
  status: 401
}
    
export type looksControllerCreateResponseSuccess = (looksControllerCreateResponse201) & {
  headers: Headers;
};
export type looksControllerCreateResponseError = (looksControllerCreateResponse400 | looksControllerCreateResponse401) & {
  headers: Headers;
};

export type looksControllerCreateResponse = (looksControllerCreateResponseSuccess | looksControllerCreateResponseError)

export const getLooksControllerCreateUrl = () => {


  

  return `/looks`
}

export const looksControllerCreate = async (createLookDto: CreateLookDto, options?: RequestInit): Promise<looksControllerCreateResponse> => {
  
  const res = await fetch(getLooksControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createLookDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: looksControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as looksControllerCreateResponse
}


/**
 * 사용자가 생성한 모든 룩 목록을 가져옵니다.
 * @summary 내 룩 목록 조회
 */
export type looksControllerFindAllResponse200 = {
  data: LookResponseDto[]
  status: 200
}

export type looksControllerFindAllResponse400 = {
  data: LooksControllerFindAll400
  status: 400
}

export type looksControllerFindAllResponse401 = {
  data: LooksControllerFindAll401
  status: 401
}
    
export type looksControllerFindAllResponseSuccess = (looksControllerFindAllResponse200) & {
  headers: Headers;
};
export type looksControllerFindAllResponseError = (looksControllerFindAllResponse400 | looksControllerFindAllResponse401) & {
  headers: Headers;
};

export type looksControllerFindAllResponse = (looksControllerFindAllResponseSuccess | looksControllerFindAllResponseError)

export const getLooksControllerFindAllUrl = () => {


  

  return `/looks`
}

export const looksControllerFindAll = async ( options?: RequestInit): Promise<looksControllerFindAllResponse> => {
  
  const res = await fetch(getLooksControllerFindAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: looksControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as looksControllerFindAllResponse
}


/**
 * 특정 룩의 상세 정보와 포함된 의류 목록을 조회합니다.
 * @summary 룩 상세 조회
 */
export type looksControllerFindOneResponse200 = {
  data: LookResponseDto
  status: 200
}

export type looksControllerFindOneResponse400 = {
  data: LooksControllerFindOne400
  status: 400
}

export type looksControllerFindOneResponse401 = {
  data: LooksControllerFindOne401
  status: 401
}

export type looksControllerFindOneResponse404 = {
  data: LooksControllerFindOne404
  status: 404
}
    
export type looksControllerFindOneResponseSuccess = (looksControllerFindOneResponse200) & {
  headers: Headers;
};
export type looksControllerFindOneResponseError = (looksControllerFindOneResponse400 | looksControllerFindOneResponse401 | looksControllerFindOneResponse404) & {
  headers: Headers;
};

export type looksControllerFindOneResponse = (looksControllerFindOneResponseSuccess | looksControllerFindOneResponseError)

export const getLooksControllerFindOneUrl = (id: string,) => {


  

  return `/looks/${id}`
}

export const looksControllerFindOne = async (id: string, options?: RequestInit): Promise<looksControllerFindOneResponse> => {
  
  const res = await fetch(getLooksControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: looksControllerFindOneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as looksControllerFindOneResponse
}


/**
 * 룩의 이름, 태그, 구성 아이템을 수정합니다.
 * @summary 룩 정보 수정
 */
export type looksControllerUpdateResponse200 = {
  data: LookResponseDto
  status: 200
}

export type looksControllerUpdateResponse400 = {
  data: LooksControllerUpdate400
  status: 400
}

export type looksControllerUpdateResponse401 = {
  data: LooksControllerUpdate401
  status: 401
}

export type looksControllerUpdateResponse404 = {
  data: LooksControllerUpdate404
  status: 404
}
    
export type looksControllerUpdateResponseSuccess = (looksControllerUpdateResponse200) & {
  headers: Headers;
};
export type looksControllerUpdateResponseError = (looksControllerUpdateResponse400 | looksControllerUpdateResponse401 | looksControllerUpdateResponse404) & {
  headers: Headers;
};

export type looksControllerUpdateResponse = (looksControllerUpdateResponseSuccess | looksControllerUpdateResponseError)

export const getLooksControllerUpdateUrl = (id: string,) => {


  

  return `/looks/${id}`
}

export const looksControllerUpdate = async (id: string,
    updateLookDto: UpdateLookDto, options?: RequestInit): Promise<looksControllerUpdateResponse> => {
  
  const res = await fetch(getLooksControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateLookDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: looksControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as looksControllerUpdateResponse
}


/**
 * 생성된 룩을 삭제합니다.
 * @summary 룩 삭제
 */
export type looksControllerRemoveResponse200 = {
  data: LookDeleteResponseDto
  status: 200
}

export type looksControllerRemoveResponse400 = {
  data: LooksControllerRemove400
  status: 400
}

export type looksControllerRemoveResponse401 = {
  data: LooksControllerRemove401
  status: 401
}

export type looksControllerRemoveResponse404 = {
  data: LooksControllerRemove404
  status: 404
}
    
export type looksControllerRemoveResponseSuccess = (looksControllerRemoveResponse200) & {
  headers: Headers;
};
export type looksControllerRemoveResponseError = (looksControllerRemoveResponse400 | looksControllerRemoveResponse401 | looksControllerRemoveResponse404) & {
  headers: Headers;
};

export type looksControllerRemoveResponse = (looksControllerRemoveResponseSuccess | looksControllerRemoveResponseError)

export const getLooksControllerRemoveUrl = (id: string,) => {


  

  return `/looks/${id}`
}

export const looksControllerRemove = async (id: string, options?: RequestInit): Promise<looksControllerRemoveResponse> => {
  
  const res = await fetch(getLooksControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: looksControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as looksControllerRemoveResponse
}


/**
 * @summary 룩 좋아요 등록
 */
export type looksControllerFavoriteResponse200 = {
  data: LookFavoriteResponseDto
  status: 200
}

export type looksControllerFavoriteResponse400 = {
  data: LooksControllerFavorite400
  status: 400
}

export type looksControllerFavoriteResponse401 = {
  data: LooksControllerFavorite401
  status: 401
}

export type looksControllerFavoriteResponse404 = {
  data: LooksControllerFavorite404
  status: 404
}
    
export type looksControllerFavoriteResponseSuccess = (looksControllerFavoriteResponse200) & {
  headers: Headers;
};
export type looksControllerFavoriteResponseError = (looksControllerFavoriteResponse400 | looksControllerFavoriteResponse401 | looksControllerFavoriteResponse404) & {
  headers: Headers;
};

export type looksControllerFavoriteResponse = (looksControllerFavoriteResponseSuccess | looksControllerFavoriteResponseError)

export const getLooksControllerFavoriteUrl = (id: string,) => {


  

  return `/looks/${id}/favorite`
}

export const looksControllerFavorite = async (id: string, options?: RequestInit): Promise<looksControllerFavoriteResponse> => {
  
  const res = await fetch(getLooksControllerFavoriteUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: looksControllerFavoriteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as looksControllerFavoriteResponse
}


/**
 * @summary 룩 좋아요 해제
 */
export type looksControllerUnfavoriteResponse200 = {
  data: LookFavoriteResponseDto
  status: 200
}

export type looksControllerUnfavoriteResponse400 = {
  data: LooksControllerUnfavorite400
  status: 400
}

export type looksControllerUnfavoriteResponse401 = {
  data: LooksControllerUnfavorite401
  status: 401
}

export type looksControllerUnfavoriteResponse404 = {
  data: LooksControllerUnfavorite404
  status: 404
}
    
export type looksControllerUnfavoriteResponseSuccess = (looksControllerUnfavoriteResponse200) & {
  headers: Headers;
};
export type looksControllerUnfavoriteResponseError = (looksControllerUnfavoriteResponse400 | looksControllerUnfavoriteResponse401 | looksControllerUnfavoriteResponse404) & {
  headers: Headers;
};

export type looksControllerUnfavoriteResponse = (looksControllerUnfavoriteResponseSuccess | looksControllerUnfavoriteResponseError)

export const getLooksControllerUnfavoriteUrl = (id: string,) => {


  

  return `/looks/${id}/favorite`
}

export const looksControllerUnfavorite = async (id: string, options?: RequestInit): Promise<looksControllerUnfavoriteResponse> => {
  
  const res = await fetch(getLooksControllerUnfavoriteUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: looksControllerUnfavoriteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as looksControllerUnfavoriteResponse
}


