/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  CreateNotificationDevDto,
  NotificationListResponseDto,
  NotificationsControllerCreateDev400,
  NotificationsControllerCreateDev401,
  NotificationsControllerList400,
  NotificationsControllerList401,
  NotificationsControllerListParams,
  NotificationsControllerMarkAllRead401,
  NotificationsControllerMarkRead400,
  NotificationsControllerMarkRead401,
  NotificationsControllerMarkRead404,
  NotificationsControllerUnreadCount401,
  ReadAllNotificationsResponseDto,
  ReadNotificationResponseDto,
  UnreadCountResponseDto
} from '../orvalSchemas';



/**
 * 실시간 알림은 WebSocket namespace `/notifications`를 사용합니다. 연결 인증은 `auth.token`, `Authorization` 헤더 또는 `accessToken` 쿠키를 사용할 수 있고, 서버는 `notification.created` 이벤트를 발행합니다. 상세 사용법은 `docs/realtime-notifications.md`를 참고하세요.
 * @summary 알림 목록 조회
 */
export type notificationsControllerListResponse200 = {
  data: NotificationListResponseDto
  status: 200
}

export type notificationsControllerListResponse400 = {
  data: NotificationsControllerList400
  status: 400
}

export type notificationsControllerListResponse401 = {
  data: NotificationsControllerList401
  status: 401
}
    
export type notificationsControllerListResponseSuccess = (notificationsControllerListResponse200) & {
  headers: Headers;
};
export type notificationsControllerListResponseError = (notificationsControllerListResponse400 | notificationsControllerListResponse401) & {
  headers: Headers;
};

export type notificationsControllerListResponse = (notificationsControllerListResponseSuccess | notificationsControllerListResponseError)

export const getNotificationsControllerListUrl = (params?: NotificationsControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/notifications?${stringifiedParams}` : `/notifications`
}

export const notificationsControllerList = async (params?: NotificationsControllerListParams, options?: RequestInit): Promise<notificationsControllerListResponse> => {
  
  const res = await fetch(getNotificationsControllerListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: notificationsControllerListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notificationsControllerListResponse
}


/**
 * WebSocket 실시간 이벤트를 받더라도 앱 복귀 또는 연결 복구 시 이 API로 unread count를 재동기화하는 것을 권장합니다.
 * @summary 읽지 않은 알림 개수 조회
 */
export type notificationsControllerUnreadCountResponse200 = {
  data: UnreadCountResponseDto
  status: 200
}

export type notificationsControllerUnreadCountResponse401 = {
  data: NotificationsControllerUnreadCount401
  status: 401
}
    
export type notificationsControllerUnreadCountResponseSuccess = (notificationsControllerUnreadCountResponse200) & {
  headers: Headers;
};
export type notificationsControllerUnreadCountResponseError = (notificationsControllerUnreadCountResponse401) & {
  headers: Headers;
};

export type notificationsControllerUnreadCountResponse = (notificationsControllerUnreadCountResponseSuccess | notificationsControllerUnreadCountResponseError)

export const getNotificationsControllerUnreadCountUrl = () => {


  

  return `/notifications/unread-count`
}

export const notificationsControllerUnreadCount = async ( options?: RequestInit): Promise<notificationsControllerUnreadCountResponse> => {
  
  const res = await fetch(getNotificationsControllerUnreadCountUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: notificationsControllerUnreadCountResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notificationsControllerUnreadCountResponse
}


/**
 * @summary 알림 읽음 처리
 */
export type notificationsControllerMarkReadResponse200 = {
  data: ReadNotificationResponseDto
  status: 200
}

export type notificationsControllerMarkReadResponse400 = {
  data: NotificationsControllerMarkRead400
  status: 400
}

export type notificationsControllerMarkReadResponse401 = {
  data: NotificationsControllerMarkRead401
  status: 401
}

export type notificationsControllerMarkReadResponse404 = {
  data: NotificationsControllerMarkRead404
  status: 404
}
    
export type notificationsControllerMarkReadResponseSuccess = (notificationsControllerMarkReadResponse200) & {
  headers: Headers;
};
export type notificationsControllerMarkReadResponseError = (notificationsControllerMarkReadResponse400 | notificationsControllerMarkReadResponse401 | notificationsControllerMarkReadResponse404) & {
  headers: Headers;
};

export type notificationsControllerMarkReadResponse = (notificationsControllerMarkReadResponseSuccess | notificationsControllerMarkReadResponseError)

export const getNotificationsControllerMarkReadUrl = (id: string,) => {


  

  return `/notifications/${id}/read`
}

export const notificationsControllerMarkRead = async (id: string, options?: RequestInit): Promise<notificationsControllerMarkReadResponse> => {
  
  const res = await fetch(getNotificationsControllerMarkReadUrl(id),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: notificationsControllerMarkReadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notificationsControllerMarkReadResponse
}


/**
 * @summary 전체 알림 읽음 처리
 */
export type notificationsControllerMarkAllReadResponse200 = {
  data: ReadAllNotificationsResponseDto
  status: 200
}

export type notificationsControllerMarkAllReadResponse401 = {
  data: NotificationsControllerMarkAllRead401
  status: 401
}
    
export type notificationsControllerMarkAllReadResponseSuccess = (notificationsControllerMarkAllReadResponse200) & {
  headers: Headers;
};
export type notificationsControllerMarkAllReadResponseError = (notificationsControllerMarkAllReadResponse401) & {
  headers: Headers;
};

export type notificationsControllerMarkAllReadResponse = (notificationsControllerMarkAllReadResponseSuccess | notificationsControllerMarkAllReadResponseError)

export const getNotificationsControllerMarkAllReadUrl = () => {


  

  return `/notifications/read-all`
}

export const notificationsControllerMarkAllRead = async ( options?: RequestInit): Promise<notificationsControllerMarkAllReadResponse> => {
  
  const res = await fetch(getNotificationsControllerMarkAllReadUrl(),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: notificationsControllerMarkAllReadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notificationsControllerMarkAllReadResponse
}


/**
 * 운영 환경에서는 사용할 수 없습니다.
 * @summary [개발용] 알림 수동 생성
 */
export type notificationsControllerCreateDevResponse200 = {
  data: ReadNotificationResponseDto
  status: 200
}

export type notificationsControllerCreateDevResponse400 = {
  data: NotificationsControllerCreateDev400
  status: 400
}

export type notificationsControllerCreateDevResponse401 = {
  data: NotificationsControllerCreateDev401
  status: 401
}
    
export type notificationsControllerCreateDevResponseSuccess = (notificationsControllerCreateDevResponse200) & {
  headers: Headers;
};
export type notificationsControllerCreateDevResponseError = (notificationsControllerCreateDevResponse400 | notificationsControllerCreateDevResponse401) & {
  headers: Headers;
};

export type notificationsControllerCreateDevResponse = (notificationsControllerCreateDevResponseSuccess | notificationsControllerCreateDevResponseError)

export const getNotificationsControllerCreateDevUrl = () => {


  

  return `/notifications/dev`
}

export const notificationsControllerCreateDev = async (createNotificationDevDto: CreateNotificationDevDto, options?: RequestInit): Promise<notificationsControllerCreateDevResponse> => {
  
  const res = await fetch(getNotificationsControllerCreateDevUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createNotificationDevDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: notificationsControllerCreateDevResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notificationsControllerCreateDevResponse
}


