/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  CreateLookRecommendationDto,
  LookRecommendationResponseDto,
  RecommendationsControllerGenerateTestImage400,
  RecommendationsControllerGenerateTestImage401,
  RecommendationsControllerGenerateTestImage403,
  RecommendationsControllerGenerateTestImageBody,
  RecommendationsControllerRecommendLook400,
  RecommendationsControllerRecommendLook401,
  RecommendationsControllerRecommendLookPublic400,
  RecommendationsControllerRecommendLookPublicParams,
  TestImageGenerationResponseDto
} from '../orvalSchemas';



/**
 * 로그인 없이 코디를 추천합니다. 좌표 미지정 시 서울(37.5665, 126.978), 성별 미지정 시 FEMALE 기준으로 처리합니다.
 * @summary 날씨 기반 코디 추천 (Public)
 */
export type recommendationsControllerRecommendLookPublicResponse200 = {
  data: LookRecommendationResponseDto
  status: 200
}

export type recommendationsControllerRecommendLookPublicResponse400 = {
  data: RecommendationsControllerRecommendLookPublic400
  status: 400
}
    
export type recommendationsControllerRecommendLookPublicResponseSuccess = (recommendationsControllerRecommendLookPublicResponse200) & {
  headers: Headers;
};
export type recommendationsControllerRecommendLookPublicResponseError = (recommendationsControllerRecommendLookPublicResponse400) & {
  headers: Headers;
};

export type recommendationsControllerRecommendLookPublicResponse = (recommendationsControllerRecommendLookPublicResponseSuccess | recommendationsControllerRecommendLookPublicResponseError)

export const getRecommendationsControllerRecommendLookPublicUrl = (params?: RecommendationsControllerRecommendLookPublicParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/recommendations/look?${stringifiedParams}` : `/recommendations/look`
}

export const recommendationsControllerRecommendLookPublic = async (params?: RecommendationsControllerRecommendLookPublicParams, options?: RequestInit): Promise<recommendationsControllerRecommendLookPublicResponse> => {
  
  const res = await fetch(getRecommendationsControllerRecommendLookPublicUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: recommendationsControllerRecommendLookPublicResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as recommendationsControllerRecommendLookPublicResponse
}


/**
 * 현재 날씨 데이터를 기반으로 코디를 추천하고 AI 이미지를 생성합니다. 좌표 미지정 시 서울(37.5665, 126.978), 성별 미지정 시 FEMALE 기준으로 처리합니다.
 * @summary 날씨 기반 코디 추천 및 이미지 생성
 */
export type recommendationsControllerRecommendLookResponse200 = {
  data: LookRecommendationResponseDto
  status: 200
}

export type recommendationsControllerRecommendLookResponse400 = {
  data: RecommendationsControllerRecommendLook400
  status: 400
}

export type recommendationsControllerRecommendLookResponse401 = {
  data: RecommendationsControllerRecommendLook401
  status: 401
}
    
export type recommendationsControllerRecommendLookResponseSuccess = (recommendationsControllerRecommendLookResponse200) & {
  headers: Headers;
};
export type recommendationsControllerRecommendLookResponseError = (recommendationsControllerRecommendLookResponse400 | recommendationsControllerRecommendLookResponse401) & {
  headers: Headers;
};

export type recommendationsControllerRecommendLookResponse = (recommendationsControllerRecommendLookResponseSuccess | recommendationsControllerRecommendLookResponseError)

export const getRecommendationsControllerRecommendLookUrl = () => {


  

  return `/recommendations/look`
}

export const recommendationsControllerRecommendLook = async (createLookRecommendationDto: CreateLookRecommendationDto, options?: RequestInit): Promise<recommendationsControllerRecommendLookResponse> => {
  
  const res = await fetch(getRecommendationsControllerRecommendLookUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createLookRecommendationDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: recommendationsControllerRecommendLookResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as recommendationsControllerRecommendLookResponse
}


/**
 * 현재 위치의 날씨 데이터 + 사용자 프롬프트 + 첨부 이미지를 조합하여 AI 이미지를 생성합니다. Production 환경에서는 사용할 수 없습니다.
 * @summary [DEV] 날씨 기반 테스트 이미지 생성
 */
export type recommendationsControllerGenerateTestImageResponse200 = {
  data: TestImageGenerationResponseDto
  status: 200
}

export type recommendationsControllerGenerateTestImageResponse400 = {
  data: RecommendationsControllerGenerateTestImage400
  status: 400
}

export type recommendationsControllerGenerateTestImageResponse401 = {
  data: RecommendationsControllerGenerateTestImage401
  status: 401
}

export type recommendationsControllerGenerateTestImageResponse403 = {
  data: RecommendationsControllerGenerateTestImage403
  status: 403
}
    
export type recommendationsControllerGenerateTestImageResponseSuccess = (recommendationsControllerGenerateTestImageResponse200) & {
  headers: Headers;
};
export type recommendationsControllerGenerateTestImageResponseError = (recommendationsControllerGenerateTestImageResponse400 | recommendationsControllerGenerateTestImageResponse401 | recommendationsControllerGenerateTestImageResponse403) & {
  headers: Headers;
};

export type recommendationsControllerGenerateTestImageResponse = (recommendationsControllerGenerateTestImageResponseSuccess | recommendationsControllerGenerateTestImageResponseError)

export const getRecommendationsControllerGenerateTestImageUrl = () => {


  

  return `/recommendations/test/generate-image`
}

export const recommendationsControllerGenerateTestImage = async (recommendationsControllerGenerateTestImageBody: RecommendationsControllerGenerateTestImageBody, options?: RequestInit): Promise<recommendationsControllerGenerateTestImageResponse> => {
    const formData = new FormData();
if(recommendationsControllerGenerateTestImageBody.latitude !== undefined) {
 formData.append(`latitude`, recommendationsControllerGenerateTestImageBody.latitude.toString())
 }
if(recommendationsControllerGenerateTestImageBody.longitude !== undefined) {
 formData.append(`longitude`, recommendationsControllerGenerateTestImageBody.longitude.toString())
 }
formData.append(`prompt`, recommendationsControllerGenerateTestImageBody.prompt);
if(recommendationsControllerGenerateTestImageBody.image !== undefined) {
 formData.append(`image`, recommendationsControllerGenerateTestImageBody.image);
 }

  const res = await fetch(getRecommendationsControllerGenerateTestImageUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: recommendationsControllerGenerateTestImageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as recommendationsControllerGenerateTestImageResponse
}


