/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  CreateShareLinkDto,
  ShareLinkDeleteResponseDto,
  ShareLinkDetailResponseDto,
  ShareLinkResponseDto,
  ShareLinkUpdateResponseDto,
  SharesControllerCreate400,
  SharesControllerCreate401,
  SharesControllerFindByPath400,
  SharesControllerFindByPath404,
  SharesControllerRemove400,
  SharesControllerRemove401,
  SharesControllerRemove404,
  SharesControllerUpdate400,
  SharesControllerUpdate401,
  SharesControllerUpdate404,
  UpdateShareLinkDto
} from '../orvalSchemas';



/**
 * 고유 경로(path)를 통해 공유된 룩의 정보를 조회합니다. (인증 불필요)
 * @summary 공유된 룩 상세 조회
 */
export type sharesControllerFindByPathResponse200 = {
  data: ShareLinkDetailResponseDto
  status: 200
}

export type sharesControllerFindByPathResponse400 = {
  data: SharesControllerFindByPath400
  status: 400
}

export type sharesControllerFindByPathResponse404 = {
  data: SharesControllerFindByPath404
  status: 404
}
    
export type sharesControllerFindByPathResponseSuccess = (sharesControllerFindByPathResponse200) & {
  headers: Headers;
};
export type sharesControllerFindByPathResponseError = (sharesControllerFindByPathResponse400 | sharesControllerFindByPathResponse404) & {
  headers: Headers;
};

export type sharesControllerFindByPathResponse = (sharesControllerFindByPathResponseSuccess | sharesControllerFindByPathResponseError)

export const getSharesControllerFindByPathUrl = (path: string,) => {


  

  return `/shares/${path}`
}

export const sharesControllerFindByPath = async (path: string, options?: RequestInit): Promise<sharesControllerFindByPathResponse> => {
  
  const res = await fetch(getSharesControllerFindByPathUrl(path),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sharesControllerFindByPathResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sharesControllerFindByPathResponse
}


/**
 * 특정 룩에 대한 고유한 공유 링크를 생성합니다.
 * @summary 공유 링크 생성
 */
export type sharesControllerCreateResponse201 = {
  data: ShareLinkResponseDto
  status: 201
}

export type sharesControllerCreateResponse400 = {
  data: SharesControllerCreate400
  status: 400
}

export type sharesControllerCreateResponse401 = {
  data: SharesControllerCreate401
  status: 401
}
    
export type sharesControllerCreateResponseSuccess = (sharesControllerCreateResponse201) & {
  headers: Headers;
};
export type sharesControllerCreateResponseError = (sharesControllerCreateResponse400 | sharesControllerCreateResponse401) & {
  headers: Headers;
};

export type sharesControllerCreateResponse = (sharesControllerCreateResponseSuccess | sharesControllerCreateResponseError)

export const getSharesControllerCreateUrl = () => {


  

  return `/shares`
}

export const sharesControllerCreate = async (createShareLinkDto: CreateShareLinkDto, options?: RequestInit): Promise<sharesControllerCreateResponse> => {
  
  const res = await fetch(getSharesControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createShareLinkDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sharesControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sharesControllerCreateResponse
}


/**
 * 공유 링크의 활성화 상태나 만료일을 수정합니다.
 * @summary 공유 링크 정보 수정
 */
export type sharesControllerUpdateResponse200 = {
  data: ShareLinkUpdateResponseDto
  status: 200
}

export type sharesControllerUpdateResponse400 = {
  data: SharesControllerUpdate400
  status: 400
}

export type sharesControllerUpdateResponse401 = {
  data: SharesControllerUpdate401
  status: 401
}

export type sharesControllerUpdateResponse404 = {
  data: SharesControllerUpdate404
  status: 404
}
    
export type sharesControllerUpdateResponseSuccess = (sharesControllerUpdateResponse200) & {
  headers: Headers;
};
export type sharesControllerUpdateResponseError = (sharesControllerUpdateResponse400 | sharesControllerUpdateResponse401 | sharesControllerUpdateResponse404) & {
  headers: Headers;
};

export type sharesControllerUpdateResponse = (sharesControllerUpdateResponseSuccess | sharesControllerUpdateResponseError)

export const getSharesControllerUpdateUrl = (id: string,) => {


  

  return `/shares/${id}`
}

export const sharesControllerUpdate = async (id: string,
    updateShareLinkDto: UpdateShareLinkDto, options?: RequestInit): Promise<sharesControllerUpdateResponse> => {
  
  const res = await fetch(getSharesControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateShareLinkDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sharesControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sharesControllerUpdateResponse
}


/**
 * 발급된 공유 링크를 삭제합니다.
 * @summary 공유 링크 삭제
 */
export type sharesControllerRemoveResponse200 = {
  data: ShareLinkDeleteResponseDto
  status: 200
}

export type sharesControllerRemoveResponse400 = {
  data: SharesControllerRemove400
  status: 400
}

export type sharesControllerRemoveResponse401 = {
  data: SharesControllerRemove401
  status: 401
}

export type sharesControllerRemoveResponse404 = {
  data: SharesControllerRemove404
  status: 404
}
    
export type sharesControllerRemoveResponseSuccess = (sharesControllerRemoveResponse200) & {
  headers: Headers;
};
export type sharesControllerRemoveResponseError = (sharesControllerRemoveResponse400 | sharesControllerRemoveResponse401 | sharesControllerRemoveResponse404) & {
  headers: Headers;
};

export type sharesControllerRemoveResponse = (sharesControllerRemoveResponseSuccess | sharesControllerRemoveResponseError)

export const getSharesControllerRemoveUrl = (id: string,) => {


  

  return `/shares/${id}`
}

export const sharesControllerRemove = async (id: string, options?: RequestInit): Promise<sharesControllerRemoveResponse> => {
  
  const res = await fetch(getSharesControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sharesControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sharesControllerRemoveResponse
}


