/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  CompleteUploadDto,
  CompleteUploadResponseDto,
  CreatePresignedUrlDto,
  PresignUploadResponseDto,
  TestUploadResponseDto,
  UploadsControllerCompleteUpload400,
  UploadsControllerCompleteUpload401,
  UploadsControllerCreatePresignedUrl400,
  UploadsControllerCreatePresignedUrl401,
  UploadsControllerTestUpload400,
  UploadsControllerTestUpload401,
  UploadsControllerTestUploadBody
} from '../orvalSchemas';



/**
 * Supabase Storage에 파일을 직접 업로드하기 위한 보안 URL을 발급합니다.
 * @summary 업로드용 Presigned URL 발급
 */
export type uploadsControllerCreatePresignedUrlResponse201 = {
  data: PresignUploadResponseDto
  status: 201
}

export type uploadsControllerCreatePresignedUrlResponse400 = {
  data: UploadsControllerCreatePresignedUrl400
  status: 400
}

export type uploadsControllerCreatePresignedUrlResponse401 = {
  data: UploadsControllerCreatePresignedUrl401
  status: 401
}
    
export type uploadsControllerCreatePresignedUrlResponseSuccess = (uploadsControllerCreatePresignedUrlResponse201) & {
  headers: Headers;
};
export type uploadsControllerCreatePresignedUrlResponseError = (uploadsControllerCreatePresignedUrlResponse400 | uploadsControllerCreatePresignedUrlResponse401) & {
  headers: Headers;
};

export type uploadsControllerCreatePresignedUrlResponse = (uploadsControllerCreatePresignedUrlResponseSuccess | uploadsControllerCreatePresignedUrlResponseError)

export const getUploadsControllerCreatePresignedUrlUrl = () => {


  

  return `/uploads/presign`
}

export const uploadsControllerCreatePresignedUrl = async (createPresignedUrlDto: CreatePresignedUrlDto, options?: RequestInit): Promise<uploadsControllerCreatePresignedUrlResponse> => {
  
  const res = await fetch(getUploadsControllerCreatePresignedUrlUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPresignedUrlDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: uploadsControllerCreatePresignedUrlResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadsControllerCreatePresignedUrlResponse
}


/**
 * 파일 업로드가 완료되었음을 서버에 알리고 상태를 갱신합니다.
 * @summary 업로드 완료 처리
 */
export type uploadsControllerCompleteUploadResponse200 = {
  data: CompleteUploadResponseDto
  status: 200
}

export type uploadsControllerCompleteUploadResponse400 = {
  data: UploadsControllerCompleteUpload400
  status: 400
}

export type uploadsControllerCompleteUploadResponse401 = {
  data: UploadsControllerCompleteUpload401
  status: 401
}
    
export type uploadsControllerCompleteUploadResponseSuccess = (uploadsControllerCompleteUploadResponse200) & {
  headers: Headers;
};
export type uploadsControllerCompleteUploadResponseError = (uploadsControllerCompleteUploadResponse400 | uploadsControllerCompleteUploadResponse401) & {
  headers: Headers;
};

export type uploadsControllerCompleteUploadResponse = (uploadsControllerCompleteUploadResponseSuccess | uploadsControllerCompleteUploadResponseError)

export const getUploadsControllerCompleteUploadUrl = () => {


  

  return `/uploads/complete`
}

export const uploadsControllerCompleteUpload = async (completeUploadDto: CompleteUploadDto, options?: RequestInit): Promise<uploadsControllerCompleteUploadResponse> => {
  
  const res = await fetch(getUploadsControllerCompleteUploadUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      completeUploadDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: uploadsControllerCompleteUploadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadsControllerCompleteUploadResponse
}


/**
 * 파일을 받아 presign → 업로드 → complete 전체 플로우를 한번에 처리합니다. 테스트/개발용입니다.
 * @summary 테스트용 통합 업로드
 */
export type uploadsControllerTestUploadResponse200 = {
  data: TestUploadResponseDto
  status: 200
}

export type uploadsControllerTestUploadResponse400 = {
  data: UploadsControllerTestUpload400
  status: 400
}

export type uploadsControllerTestUploadResponse401 = {
  data: UploadsControllerTestUpload401
  status: 401
}
    
export type uploadsControllerTestUploadResponseSuccess = (uploadsControllerTestUploadResponse200) & {
  headers: Headers;
};
export type uploadsControllerTestUploadResponseError = (uploadsControllerTestUploadResponse400 | uploadsControllerTestUploadResponse401) & {
  headers: Headers;
};

export type uploadsControllerTestUploadResponse = (uploadsControllerTestUploadResponseSuccess | uploadsControllerTestUploadResponseError)

export const getUploadsControllerTestUploadUrl = () => {


  

  return `/uploads/test-upload`
}

export const uploadsControllerTestUpload = async (uploadsControllerTestUploadBody: UploadsControllerTestUploadBody, options?: RequestInit): Promise<uploadsControllerTestUploadResponse> => {
    const formData = new FormData();
formData.append(`file`, uploadsControllerTestUploadBody.file);
if(uploadsControllerTestUploadBody.type !== undefined) {
 formData.append(`type`, uploadsControllerTestUploadBody.type);
 }

  const res = await fetch(getUploadsControllerTestUploadUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: uploadsControllerTestUploadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadsControllerTestUploadResponse
}


