/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type {
  ResetNicknameResponseDto,
  UpdateProfileDto,
  UpdateProfileResponseDto,
  UserProfileResponseDto,
  UsersControllerGetMe400,
  UsersControllerGetMe401,
  UsersControllerResetData400,
  UsersControllerResetData401,
  UsersControllerResetNickname400,
  UsersControllerResetNickname401,
  UsersControllerUpdateProfile400,
  UsersControllerUpdateProfile401
} from '../orvalSchemas';



/**
 * 현재 로그인한 사용자의 프로필 정보를 가져옵니다.
 * @summary 내 프로필 조회
 */
export type usersControllerGetMeResponse200 = {
  data: UserProfileResponseDto
  status: 200
}

export type usersControllerGetMeResponse400 = {
  data: UsersControllerGetMe400
  status: 400
}

export type usersControllerGetMeResponse401 = {
  data: UsersControllerGetMe401
  status: 401
}
    
export type usersControllerGetMeResponseSuccess = (usersControllerGetMeResponse200) & {
  headers: Headers;
};
export type usersControllerGetMeResponseError = (usersControllerGetMeResponse400 | usersControllerGetMeResponse401) & {
  headers: Headers;
};

export type usersControllerGetMeResponse = (usersControllerGetMeResponseSuccess | usersControllerGetMeResponseError)

export const getUsersControllerGetMeUrl = () => {


  

  return `/users/me`
}

export const usersControllerGetMe = async ( options?: RequestInit): Promise<usersControllerGetMeResponse> => {
  
  const res = await fetch(getUsersControllerGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerGetMeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerGetMeResponse
}


/**
 * 닉네임 또는 프로필 이미지를 수정합니다.
 * @summary 프로필 수정
 */
export type usersControllerUpdateProfileResponse200 = {
  data: UpdateProfileResponseDto
  status: 200
}

export type usersControllerUpdateProfileResponse400 = {
  data: UsersControllerUpdateProfile400
  status: 400
}

export type usersControllerUpdateProfileResponse401 = {
  data: UsersControllerUpdateProfile401
  status: 401
}
    
export type usersControllerUpdateProfileResponseSuccess = (usersControllerUpdateProfileResponse200) & {
  headers: Headers;
};
export type usersControllerUpdateProfileResponseError = (usersControllerUpdateProfileResponse400 | usersControllerUpdateProfileResponse401) & {
  headers: Headers;
};

export type usersControllerUpdateProfileResponse = (usersControllerUpdateProfileResponseSuccess | usersControllerUpdateProfileResponseError)

export const getUsersControllerUpdateProfileUrl = () => {


  

  return `/users/profile`
}

export const usersControllerUpdateProfile = async (updateProfileDto: UpdateProfileDto, options?: RequestInit): Promise<usersControllerUpdateProfileResponse> => {
  
  const res = await fetch(getUsersControllerUpdateProfileUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProfileDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerUpdateProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerUpdateProfileResponse
}


/**
 * 현재 로그인한 사용자의 닉네임을 랜덤한 새 값으로 재생성합니다.
 * @summary 닉네임 랜덤 재생성
 */
export type usersControllerResetNicknameResponse200 = {
  data: ResetNicknameResponseDto
  status: 200
}

export type usersControllerResetNicknameResponse400 = {
  data: UsersControllerResetNickname400
  status: 400
}

export type usersControllerResetNicknameResponse401 = {
  data: UsersControllerResetNickname401
  status: 401
}
    
export type usersControllerResetNicknameResponseSuccess = (usersControllerResetNicknameResponse200) & {
  headers: Headers;
};
export type usersControllerResetNicknameResponseError = (usersControllerResetNicknameResponse400 | usersControllerResetNicknameResponse401) & {
  headers: Headers;
};

export type usersControllerResetNicknameResponse = (usersControllerResetNicknameResponseSuccess | usersControllerResetNicknameResponseError)

export const getUsersControllerResetNicknameUrl = () => {


  

  return `/users/nickname/reset`
}

export const usersControllerResetNickname = async ( options?: RequestInit): Promise<usersControllerResetNicknameResponse> => {
  
  const res = await fetch(getUsersControllerResetNicknameUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerResetNicknameResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerResetNicknameResponse
}


/**
 * 사용자의 모든 데이터(의류, 룩 등)를 삭제합니다.
 * @summary 사용자 데이터 초기화
 */
export type usersControllerResetDataResponse204 = {
  data: void
  status: 204
}

export type usersControllerResetDataResponse400 = {
  data: UsersControllerResetData400
  status: 400
}

export type usersControllerResetDataResponse401 = {
  data: UsersControllerResetData401
  status: 401
}
    
export type usersControllerResetDataResponseSuccess = (usersControllerResetDataResponse204) & {
  headers: Headers;
};
export type usersControllerResetDataResponseError = (usersControllerResetDataResponse400 | usersControllerResetDataResponse401) & {
  headers: Headers;
};

export type usersControllerResetDataResponse = (usersControllerResetDataResponseSuccess | usersControllerResetDataResponseError)

export const getUsersControllerResetDataUrl = () => {


  

  return `/users/reset`
}

export const usersControllerResetData = async ( options?: RequestInit): Promise<usersControllerResetDataResponse> => {
  
  const res = await fetch(getUsersControllerResetDataUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerResetDataResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerResetDataResponse
}


