/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type ClothesUpdateResponseDtoCategory = typeof ClothesUpdateResponseDtoCategory[keyof typeof ClothesUpdateResponseDtoCategory];


export const ClothesUpdateResponseDtoCategory = {
  TOP: 'TOP',
  BOTTOM: 'BOTTOM',
  OUTER: 'OUTER',
  SHOES: 'SHOES',
  ACCESSORY: 'ACCESSORY',
} as const;
