/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 업로드 타입 (allowlist 기준)
 */
export type CreatePresignedUrlDtoType = typeof CreatePresignedUrlDtoType[keyof typeof CreatePresignedUrlDtoType];


export const CreatePresignedUrlDtoType = {
  clothes: 'clothes',
  profile: 'profile',
} as const;
