/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { CreateClothesDtoCategory } from './createClothesDtoCategory';

export interface CreateClothesDto {
  /** 의류 명칭 */
  title: string;
  /** 의류 카테고리 */
  category: CreateClothesDtoCategory;
  /** 의류 색상 */
  color: string;
  /** 의류 이미지 URL (업로드 완료된 URL) */
  imageUrl: string;
}
