/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface CreateLocationDto {
  /** 위치 이름 (도시/구 등) */
  name: string;
  /** 위도 */
  lat: number;
  /** 경도 */
  lon: number;
  /** 타임존 */
  timezone: string;
  /** 위치 별칭 (내 집, 회사 등) */
  alias: string;
  /** 기본 위치 설정 여부 */
  isDefault: boolean;
}
