/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 성별 (미지정 시 FEMALE)
 */
export type CreateLookRecommendationDtoGender = typeof CreateLookRecommendationDtoGender[keyof typeof CreateLookRecommendationDtoGender];


export const CreateLookRecommendationDtoGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;
