/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface CreateCommentDto {
  /** 댓글 내용 */
  content: string;
  /** 대댓글인 경우 부모 댓글 ID */
  parentCommentId?: string;
}
