/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface LookItemDto {
  /** 의류 ID (UUID) */
  clothesId: string;
  /** 아이템 정렬 순서 */
  sortOrder: number;
  /** 아이템 역할 (top, bottom 등) */
  role: string;
}
