/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { WeatherDisplayDto } from './weatherDisplayDto';

export interface RecommendationWeatherDto {
  /** 위도 */
  latitude: number;
  /** 경도 */
  longitude: number;
  display: WeatherDisplayDto;
}
