/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ShareLookDto } from './shareLookDto';

export interface ShareLinkDetailResponseDto {
  id: string;
  path: string;
  isActive: boolean;
  look: ShareLookDto;
}
