/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface SuggestClothesDto {
  /** AI에게 전달할 프롬프트 */
  prompt: string;
  /** 참조 이미지 URL (선택) */
  imageUrl?: string;
}
