/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface UpdateShareLinkDto {
  /** 공유 링크 활성화 여부 */
  isActive?: boolean;
  /** 만료 일시 */
  expiresAt?: string;
}
