/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface UpdateProfileDto {
  /** 수정할 닉네임 */
  nickname?: string;
  /** 수정할 프로필 이미지 URL */
  profileImg?: string;
}
