/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { UpdateClothesDtoCategory } from './updateClothesDtoCategory';

export interface UpdateClothesDto {
  /** 의류 명칭 */
  title?: string;
  /** 의류 카테고리 */
  category?: UpdateClothesDtoCategory;
  /** 의류 색상 */
  color?: string;
  /** 의류 이미지 URL */
  imageUrl?: string;
}
