/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 강수 형태
 */
export type WeatherDisplayDtoPrecipitationType = typeof WeatherDisplayDtoPrecipitationType[keyof typeof WeatherDisplayDtoPrecipitationType];


export const WeatherDisplayDtoPrecipitationType = {
  없음: '없음',
  비: '비',
  '비/눈': '비/눈',
  눈: '눈',
  소나기: '소나기',
} as const;
