/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { AnnouncementImagesDto } from './announcementImagesDto';

export interface AnnouncementListItemDto {
  id: string;
  title: string;
  excerpt: string;
  isPinned: boolean;
  publishedAt: string;
  createdAt: string;
  images?: AnnouncementImagesDto;
}
