/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type AnnouncementsControllerListParams = {
/**
 * 다음 페이지 커서(announcement id)
 */
cursor?: string;
/**
 * 페이지 크기 (1~50)
 */
limit?: number;
};
