/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type AuthControllerKakaoCallbackParams = {
/**
 * OAuth 인증 코드
 */
code: string;
/**
 * CSRF 방지용 상태 값
 */
state: string;
};
