/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface BackgroundRemovalRequestDto {
  /** 배경 제거할 이미지 파일 (jpeg/png/webp, 최대 5MB) */
  file: string;
}
