/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface BackgroundRemovalResponseDto {
  /** 배경 제거 결과 이미지 URL */
  url: string;
}
