/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ClothesImageVariantDto } from './clothesImageVariantDto';
import type { ClothesListItemResponseDtoCategory } from './clothesListItemResponseDtoCategory';

export interface ClothesListItemResponseDto {
  id: string;
  alias: string;
  category: ClothesListItemResponseDtoCategory;
  isLiked: boolean;
  /** 카드 UI용 파생본 (webp/jpeg) */
  cardImage?: ClothesImageVariantDto;
}
