/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type ClothesControllerGetClothesImageFormat = typeof ClothesControllerGetClothesImageFormat[keyof typeof ClothesControllerGetClothesImageFormat];


export const ClothesControllerGetClothesImageFormat = {
  webp: 'webp',
  jpeg: 'jpeg',
  both: 'both',
} as const;
