/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ClothesResponseDtoCategory } from './clothesResponseDtoCategory';

export interface ClothesResponseDto {
  id: string;
  title: string;
  category: ClothesResponseDtoCategory;
  color: string;
  imageUrl: string;
  createdAt: string;
}
