/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ClothesControllerGetClothesImageFormat } from './clothesControllerGetClothesImageFormat';

export type ClothesControllerGetClothesImageParams = {
/**
 * 반환할 파생본 종류(csv). 예: detail,thumb
 */
variant: string;
/**
 * 반환할 포맷 (기본 both)
 */
format: ClothesControllerGetClothesImageFormat;
};
