/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type ClothesUpdateResponseDtoSeasonItem = typeof ClothesUpdateResponseDtoSeasonItem[keyof typeof ClothesUpdateResponseDtoSeasonItem];


export const ClothesUpdateResponseDtoSeasonItem = {
  SPRING: 'SPRING',
  SUMMER: 'SUMMER',
  FALL: 'FALL',
  WINTER: 'WINTER',
  ALL: 'ALL',
} as const;
