/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type ClothesResponseDtoSeasonItem = typeof ClothesResponseDtoSeasonItem[keyof typeof ClothesResponseDtoSeasonItem];


export const ClothesResponseDtoSeasonItem = {
  SPRING: 'SPRING',
  SUMMER: 'SUMMER',
  FALL: 'FALL',
  WINTER: 'WINTER',
  ALL: 'ALL',
} as const;
