/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type ClothesUpdateResponseDtoMaterialItem = typeof ClothesUpdateResponseDtoMaterialItem[keyof typeof ClothesUpdateResponseDtoMaterialItem];


export const ClothesUpdateResponseDtoMaterialItem = {
  NYLON: 'NYLON',
  DOWN_FEATHER: 'DOWN_FEATHER',
  DENIM: 'DENIM',
  LYOCELL: 'LYOCELL',
  LEATHER: 'LEATHER',
  LACE: 'LACE',
  RAYON: 'RAYON',
  LINEN: 'LINEN',
  METAL: 'METAL',
  COTTON: 'COTTON',
  MOHAIR: 'MOHAIR',
  VELVET: 'VELVET',
  VISCOSE: 'VISCOSE',
  CHIFFON: 'CHIFFON',
  SUEDE: 'SUEDE',
  SPANDEX: 'SPANDEX',
  SILK: 'SILK',
  ACRYLIC: 'ACRYLIC',
  ALPACA: 'ALPACA',
  ANGORA: 'ANGORA',
  WOOL: 'WOOL',
  CASHMERE: 'CASHMERE',
  CORDUROY: 'CORDUROY',
  CUPRA: 'CUPRA',
  TWEED: 'TWEED',
  FUR: 'FUR',
  POLYESTER: 'POLYESTER',
  ETC: 'ETC',
} as const;
