/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type ClothesControllerFindAllCategory = typeof ClothesControllerFindAllCategory[keyof typeof ClothesControllerFindAllCategory];


export const ClothesControllerFindAllCategory = {
  TOP: 'TOP',
  BOTTOM: 'BOTTOM',
  OUTER: 'OUTER',
  DRESS_SKIRT: 'DRESS_SKIRT',
  SHOES: 'SHOES',
  ACCESSORY: 'ACCESSORY',
} as const;
