/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ClothesControllerFindAllCategory } from './clothesControllerFindAllCategory';

export type ClothesControllerFindAllParams = {
/**
 * 1차 카테고리 필터 (미지정 시 전체)
 */
category: ClothesControllerFindAllCategory;
};
