/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type ClothesUpdateResponseDtoColorItem = typeof ClothesUpdateResponseDtoColorItem[keyof typeof ClothesUpdateResponseDtoColorItem];


export const ClothesUpdateResponseDtoColorItem = {
  흰색: '흰색',
  아이보리: '아이보리',
  베이지: '베이지',
  연회색: '연회색',
  진회색: '진회색',
  검정: '검정',
  연노랑: '연노랑',
  노랑: '노랑',
  황색: '황색',
  주황: '주황',
  코랄: '코랄',
  빨강: '빨강',
  분홍: '분홍',
  진분홍: '진분홍',
  연두: '연두',
  초록: '초록',
  올리브: '올리브',
  다크올리브: '다크올리브',
  청록: '청록',
  카키: '카키',
  시안: '시안',
  하늘색: '하늘색',
  파랑: '파랑',
  네이비: '네이비',
  라벤더: '라벤더',
  보라: '보라',
  버건디: '버건디',
  카멜: '카멜',
  갈색: '갈색',
  다크브라운: '다크브라운',
  마젠타: '마젠타',
  골드: '골드',
  실버: '실버',
  다채색: '다채색',
} as const;
