/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ClothesUpdateResponseDtoCategory } from './clothesUpdateResponseDtoCategory';

export interface ClothesUpdateResponseDto {
  id: string;
  title: string;
  category: ClothesUpdateResponseDtoCategory;
  color: string;
  imageUrl: string;
  createdAt: string;
  updatedAt: string;
}
