/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type ClothesUpdateResponseDtoMaterialItem = typeof ClothesUpdateResponseDtoMaterialItem[keyof typeof ClothesUpdateResponseDtoMaterialItem];


export const ClothesUpdateResponseDtoMaterialItem = {
  나일론: '나일론',
  다운_페더: '다운 페더',
  데님: '데님',
  라이오셀: '라이오셀',
  레더: '레더',
  레이스: '레이스',
  레이온: '레이온',
  린넨: '린넨',
  메탈: '메탈',
  면: '면',
  모헤어: '모헤어',
  벨벳: '벨벳',
  비스코스: '비스코스',
  쉬폰: '쉬폰',
  스웨이드: '스웨이드',
  스판덱스: '스판덱스',
  실크: '실크',
  아크릴: '아크릴',
  알파카: '알파카',
  앙고라: '앙고라',
  울: '울',
  캐시미어: '캐시미어',
  코듀로이: '코듀로이',
  큐프라: '큐프라',
  트위드: '트위드',
  퍼: '퍼',
  폴리에스터: '폴리에스터',
  기타: '기타',
} as const;
