/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type ClothesResponseDtoSize = typeof ClothesResponseDtoSize[keyof typeof ClothesResponseDtoSize];


export const ClothesResponseDtoSize = {
  XS: 'XS',
  S: 'S',
  M: 'M',
  L: 'L',
  XL: 'XL',
  '2XL': '2XL',
  '3XL': '3XL',
  FREE: 'FREE',
} as const;
