/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { CommentUserDto } from './commentUserDto';

export interface CommentResponseDto {
  id: string;
  content: string;
  /** @nullable */
  parentCommentId: string | null;
  createdAt?: string;
  user: CommentUserDto;
  likeCount: number;
  isLiked: boolean;
  replies?: CommentResponseDto[];
}
