/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface CompleteUploadDto {
  /** 업로드된 파일의 경로 */
  filePath: string;
  /** 업로드 완료 검증 토큰 */
  uploadToken: string;
}
