/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface CreateAnnouncementRequestDto {
  /** 공지 제목 (필수) */
  title: string;
  /** 공지 본문 (필수) */
  body: string;
  /** 상단 고정 여부 (선택, 기본 false) */
  isPinned?: boolean;
  /** 게시 여부 (선택, 기본 true) */
  isPublished?: boolean;
  /** 게시 시각 (선택) */
  publishedAt?: string;
  /** 공지 이미지 파일 (jpeg/png/webp, 최대 10MB) */
  image?: string;
}
