/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { CreatePresignedUrlDtoContentType } from './createPresignedUrlDtoContentType';
import type { CreatePresignedUrlDtoType } from './createPresignedUrlDtoType';

export interface CreatePresignedUrlDto {
  /** 업로드 타입 (allowlist 기준) */
  type: CreatePresignedUrlDtoType;
  /** 파일 MIME 타입 */
  contentType: CreatePresignedUrlDtoContentType;
  /** 파일 크기 (bytes) */
  contentLength: number;
}
