/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface CreateShareLinkDto {
  /** 공유할 룩 ID */
  lookId: string;
  /** 만료 일시 (미사용: 서버에서 생성 시점 기준 3시간으로 고정) */
  expiresAt?: string;
}
