/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 파일 MIME 타입
 */
export type CreatePresignedUrlDtoContentType = typeof CreatePresignedUrlDtoContentType[keyof typeof CreatePresignedUrlDtoContentType];


export const CreatePresignedUrlDtoContentType = {
  'image/jpeg': 'image/jpeg',
  'image/png': 'image/png',
  'image/webp': 'image/webp',
} as const;
