/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { CreateNotificationDevDtoType } from './createNotificationDevDtoType';

export interface CreateNotificationDevDto {
  type: CreateNotificationDevDtoType;
  title: string;
  body: string;
  /** @nullable */
  link?: string | null;
}
