/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type CreateClothesDtoColorItem = typeof CreateClothesDtoColorItem[keyof typeof CreateClothesDtoColorItem];


export const CreateClothesDtoColorItem = {
  WHITE: 'WHITE',
  IVORY: 'IVORY',
  BEIGE: 'BEIGE',
  LIGHT_GRAY: 'LIGHT_GRAY',
  DARK_GRAY: 'DARK_GRAY',
  BLACK: 'BLACK',
  LIGHT_YELLOW: 'LIGHT_YELLOW',
  YELLOW: 'YELLOW',
  AMBER: 'AMBER',
  ORANGE: 'ORANGE',
  CORAL: 'CORAL',
  RED: 'RED',
  PINK: 'PINK',
  DEEP_PINK: 'DEEP_PINK',
  LIGHT_GREEN: 'LIGHT_GREEN',
  GREEN: 'GREEN',
  OLIVE: 'OLIVE',
  DARK_OLIVE: 'DARK_OLIVE',
  TEAL: 'TEAL',
  KHAKI: 'KHAKI',
  CYAN: 'CYAN',
  SKY_BLUE: 'SKY_BLUE',
  BLUE: 'BLUE',
  NAVY: 'NAVY',
  LAVENDER: 'LAVENDER',
  PURPLE: 'PURPLE',
  BURGUNDY: 'BURGUNDY',
  CAMEL: 'CAMEL',
  BROWN: 'BROWN',
  DARK_BROWN: 'DARK_BROWN',
  MAGENTA: 'MAGENTA',
  GOLD: 'GOLD',
  SILVER: 'SILVER',
  MULTICOLORED: 'MULTICOLORED',
} as const;
