/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { LookItemDto } from './lookItemDto';

export interface CreateLookDto {
  /** 룩 명칭 */
  name?: string;
  /** 룩 태그 (쉼표 구분) */
  tags: string;
  /** 룩 구성 아이템 리스트 */
  items: LookItemDto[];
}
