/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface LookRecommendationDto {
  /**
   * AI가 생성한 코디 설명
   * @nullable
   */
  description: string | null;
  /**
   * 생성된 코디 이미지 URL (signed URL, 7일 유효)
   * @nullable
   */
  lookImageUrl: string | null;
}
