/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { LookItemResponseDto } from './lookItemResponseDto';

export interface LookResponseDto {
  id: string;
  name: string;
  /** 태그 문자열(쉼표 구분) */
  tags: string;
  items: LookItemResponseDto[];
  likeCount: number;
  isLiked: boolean;
}
