/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { LookClothesDto } from './lookClothesDto';

export interface LookItemResponseDto {
  id: string;
  clothesId: string;
  sortOrder: number;
  role: string;
  clothes: LookClothesDto;
}
