/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { LookRecommendationDto } from './lookRecommendationDto';
import type { LookRecommendationResponseDtoGender } from './lookRecommendationResponseDtoGender';
import type { RecommendationWeatherDto } from './recommendationWeatherDto';

export interface LookRecommendationResponseDto {
  weather: RecommendationWeatherDto;
  gender: LookRecommendationResponseDtoGender;
  recommendation: LookRecommendationDto;
}
