/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type NotificationResponseDtoType = typeof NotificationResponseDtoType[keyof typeof NotificationResponseDtoType];


export const NotificationResponseDtoType = {
  SHARE_COMMENT: 'SHARE_COMMENT',
  SHARE_EXPIRING: 'SHARE_EXPIRING',
  LOOK_READY: 'LOOK_READY',
  SYSTEM: 'SYSTEM',
} as const;
