/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type NotificationsControllerListParams = {
/**
 * 다음 페이지 커서(notification id)
 */
cursor?: string;
/**
 * 읽지 않은 알림만 조회
 */
unreadOnly?: boolean;
/**
 * 페이지 크기 (1~50)
 */
limit?: number;
};
