/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { NotificationResponseDtoType } from './notificationResponseDtoType';

export interface NotificationResponseDto {
  id: string;
  type: NotificationResponseDtoType;
  title: string;
  body: string;
  /** @nullable */
  link?: string | null;
  isRead: boolean;
  /** @nullable */
  readAt?: string | null;
  createdAt: string;
}
