/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type RecommendationsControllerGenerateTestImageBody = {
  /** 위도 (미지정 시 서울 기준) */
  latitude?: number;
  /** 경도 (미지정 시 서울 기준) */
  longitude?: number;
  /** 이미지 생성에 사용할 프롬프트 */
  prompt: string;
  /** 참조할 이미지 파일 (선택) */
  image?: Blob;
};
