/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { RecommendationsControllerRecommendLookPublicGender } from './recommendationsControllerRecommendLookPublicGender';

export type RecommendationsControllerRecommendLookPublicParams = {
/**
 * 위도 (미지정 시 서울 기준: 37.5665)
 */
latitude?: number;
/**
 * 경도 (미지정 시 서울 기준: 126.978)
 */
longitude?: number;
/**
 * 성별 (미지정 시 FEMALE)
 */
gender?: RecommendationsControllerRecommendLookPublicGender;
};
