/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ShareLookItemDto } from './shareLookItemDto';
import type { ShareUserDto } from './shareUserDto';

export interface ShareLookDto {
  id: string;
  name: string;
  tags: string;
  items: ShareLookItemDto[];
  user: ShareUserDto;
}
