/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ShareLookItemClothesDto } from './shareLookItemClothesDto';
import type { ShareLookItemImagesDto } from './shareLookItemImagesDto';

export interface ShareLookItemDto {
  id: string;
  clothesId?: string;
  sortOrder?: number;
  role?: string;
  clothes?: ShareLookItemClothesDto | null;
  images?: ShareLookItemImagesDto;
}
