/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { RecommendationWeatherDto } from './recommendationWeatherDto';

export interface TestImageGenerationResponseDto {
  weather: RecommendationWeatherDto;
  /** 사용자 프롬프트 + 날씨 정보가 포함된 전체 프롬프트 */
  prompt: string;
  /**
   * AI가 생성한 설명 텍스트
   * @nullable
   */
  text: string | null;
  /**
   * 생성된 이미지 URL (signed URL, 7일 유효)
   * @nullable
   */
  imageUrl: string | null;
}
