/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface UpdateLocationDto {
  /** 위치 별칭 */
  alias?: string;
  /** 기본 위치 설정 여부 */
  isDefault?: boolean;
}
