/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface UpdateAnnouncementRequestDto {
  title?: string;
  body?: string;
  isPinned?: boolean;
  isPublished?: boolean;
  publishedAt?: string;
  /** 공지 이미지 파일 (jpeg/png/webp, 최대 10MB) */
  image?: string;
}
