/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * [선택] 의류 카테고리
 */
export type UpdateClothesDtoCategory = typeof UpdateClothesDtoCategory[keyof typeof UpdateClothesDtoCategory];


export const UpdateClothesDtoCategory = {
  TOP: 'TOP',
  BOTTOM: 'BOTTOM',
  OUTER: 'OUTER',
  DRESS_SKIRT: 'DRESS_SKIRT',
  SHOES: 'SHOES',
  ACCESSORY: 'ACCESSORY',
} as const;
