/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { UploadsControllerTestUploadBodyType } from './uploadsControllerTestUploadBodyType';

export type UploadsControllerTestUploadBody = {
  file: Blob;
  /** 업로드 타입 (기본값: clothes) */
  type?: UploadsControllerTestUploadBodyType;
};
