/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 업로드 타입 (기본값: clothes)
 */
export type UploadsControllerTestUploadBodyType = typeof UploadsControllerTestUploadBodyType[keyof typeof UploadsControllerTestUploadBodyType];


export const UploadsControllerTestUploadBodyType = {
  clothes: 'clothes',
  profile: 'profile',
} as const;
