/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface UserProfileResponseDto {
  id: string;
  email: string;
  nickname: string;
  profileImg: string;
  isNewUser: boolean;
  createdAt: string;
  /** 삭제되지 않은 의류 개수 */
  clothesCount: number;
  /** 삭제되지 않은 룩 개수 */
  looksCount: number;
}
