/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 하늘 상태
 */
export type WeatherDisplayDtoSky = typeof WeatherDisplayDtoSky[keyof typeof WeatherDisplayDtoSky];


export const WeatherDisplayDtoSky = {
  맑음: '맑음',
  구름많음: '구름많음',
  흐림: '흐림',
} as const;
