/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { WeatherDisplayDto } from './weatherDisplayDto';

export interface WeatherResponseDto {
  locationId: string;
  tempCurrent: number;
  tempMin: number;
  tempMax: number;
  humidity: number;
  precipitation: number;
  precipitationProbability: number;
  precipitationTypeCode: number;
  windSpeed: number;
  skyCode: number;
  source: string;
  display: WeatherDisplayDto;
}
