/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Donut API
 * Donut 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { WeatherDisplayDtoPrecipitationType } from './weatherDisplayDtoPrecipitationType';
import type { WeatherDisplayDtoSky } from './weatherDisplayDtoSky';

export interface WeatherDisplayDto {
  /**
   * 위치명
   * @nullable
   */
  locationName: string | null;
  /** 하늘 상태 */
  sky: WeatherDisplayDtoSky;
  /** 강수 형태 */
  precipitationType: WeatherDisplayDtoPrecipitationType;
  /** 현재 기온 */
  tempCurrent: number;
  /** 최저 기온 */
  tempMin: number;
  /** 최고 기온 */
  tempMax: number;
  /** 풍속 */
  wind: string;
  /** 강수 확률 */
  precipitationProbability: string;
  /**
   * 날씨 메시지
   * @nullable
   */
  message: string | null;
}
